// Copyright 2026 Datum Cloud, Inc.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// The fabric-api gRPC contract between a cell's fabric-api gateway and the
// fabric-api node sidecars in its fabric-router pods, and the gateway's
// operator debug service. It is internal to galactic: the public interface is
// the LookingGlassQuery CRD, and nothing outside a cell calls these services.
//
// Every RPC is unary with a bounded result, since the end consumer is a
// Kubernetes status object. A successful Execute returns an Observation;
// every failure is a gRPC status carrying a google.rpc.ErrorInfo whose reason
// is the typed error code (domain fabric-api.datumapis.com).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: fabric/v1/fabric.proto

package fabricv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FabricService_Execute_FullMethodName = "/fabric.v1.FabricService/Execute"
	FabricService_Info_FullMethodName    = "/fabric.v1.FabricService/Info"
)

// FabricServiceClient is the client API for FabricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FabricService runs on each fabric-api node sidecar.
type FabricServiceClient interface {
	// Execute runs one query on this node. Calls with the same
	// (request_id, node, query) are deduplicated while the request lives.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Info reports this node's identity and whether diagnostics are available.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type fabricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricServiceClient(cc grpc.ClientConnInterface) FabricServiceClient {
	return &fabricServiceClient{cc}
}

func (c *fabricServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, FabricService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, FabricService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricServiceServer is the server API for FabricService service.
// All implementations must embed UnimplementedFabricServiceServer
// for forward compatibility.
//
// FabricService runs on each fabric-api node sidecar.
type FabricServiceServer interface {
	// Execute runs one query on this node. Calls with the same
	// (request_id, node, query) are deduplicated while the request lives.
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Info reports this node's identity and whether diagnostics are available.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	mustEmbedUnimplementedFabricServiceServer()
}

// UnimplementedFabricServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricServiceServer struct{}

func (UnimplementedFabricServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedFabricServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedFabricServiceServer) mustEmbedUnimplementedFabricServiceServer() {}
func (UnimplementedFabricServiceServer) testEmbeddedByValue()                       {}

// UnsafeFabricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricServiceServer will
// result in compilation errors.
type UnsafeFabricServiceServer interface {
	mustEmbedUnimplementedFabricServiceServer()
}

func RegisterFabricServiceServer(s grpc.ServiceRegistrar, srv FabricServiceServer) {
	// If the following call panics, it indicates UnimplementedFabricServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FabricService_ServiceDesc, srv)
}

func _FabricService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FabricService_ServiceDesc is the grpc.ServiceDesc for FabricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FabricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fabric.v1.FabricService",
	HandlerType: (*FabricServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _FabricService_Execute_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _FabricService_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fabric/v1/fabric.proto",
}

const (
	FabricGatewayService_Query_FullMethodName     = "/fabric.v1.FabricGatewayService/Query"
	FabricGatewayService_ListNodes_FullMethodName = "/fabric.v1.FabricGatewayService/ListNodes"
)

// FabricGatewayServiceClient is the client API for FabricGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FabricGatewayService is the gateway's operator debug service. It applies
// the same validation and limits as federated execution.
type FabricGatewayServiceClient interface {
	// Query runs a query on the cell's eligible nodes, or a subset of them.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// ListNodes lists the nodes the gateway would execute on.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
}

type fabricGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricGatewayServiceClient(cc grpc.ClientConnInterface) FabricGatewayServiceClient {
	return &fabricGatewayServiceClient{cc}
}

func (c *fabricGatewayServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, FabricGatewayService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricGatewayServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, FabricGatewayService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricGatewayServiceServer is the server API for FabricGatewayService service.
// All implementations must embed UnimplementedFabricGatewayServiceServer
// for forward compatibility.
//
// FabricGatewayService is the gateway's operator debug service. It applies
// the same validation and limits as federated execution.
type FabricGatewayServiceServer interface {
	// Query runs a query on the cell's eligible nodes, or a subset of them.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// ListNodes lists the nodes the gateway would execute on.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	mustEmbedUnimplementedFabricGatewayServiceServer()
}

// UnimplementedFabricGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricGatewayServiceServer struct{}

func (UnimplementedFabricGatewayServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedFabricGatewayServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedFabricGatewayServiceServer) mustEmbedUnimplementedFabricGatewayServiceServer() {}
func (UnimplementedFabricGatewayServiceServer) testEmbeddedByValue()                              {}

// UnsafeFabricGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricGatewayServiceServer will
// result in compilation errors.
type UnsafeFabricGatewayServiceServer interface {
	mustEmbedUnimplementedFabricGatewayServiceServer()
}

func RegisterFabricGatewayServiceServer(s grpc.ServiceRegistrar, srv FabricGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedFabricGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FabricGatewayService_ServiceDesc, srv)
}

func _FabricGatewayService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricGatewayServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricGatewayService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricGatewayServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FabricGatewayService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricGatewayServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FabricGatewayService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricGatewayServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FabricGatewayService_ServiceDesc is the grpc.ServiceDesc for FabricGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FabricGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fabric.v1.FabricGatewayService",
	HandlerType: (*FabricGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _FabricGatewayService_Query_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _FabricGatewayService_ListNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fabric/v1/fabric.proto",
}
