// Copyright 2026 Datum Cloud, Inc.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// The fabric-api gRPC contract between a cell's fabric-api gateway and the
// fabric-api node sidecars in its fabric-router pods, and the gateway's
// operator debug service. It is internal to galactic: the public interface is
// the LookingGlassQuery CRD, and nothing outside a cell calls these services.
//
// Every RPC is unary with a bounded result, since the end consumer is a
// Kubernetes status object. A successful Execute returns an Observation;
// every failure is a gRPC status carrying a google.rpc.ErrorInfo whose reason
// is the typed error code (domain fabric-api.datumapis.com).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: fabric/v1/fabric.proto

package fabricv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED     QueryType = 0
	QueryType_QUERY_TYPE_ROUTE_LOOKUP    QueryType = 1
	QueryType_QUERY_TYPE_AS_PATH         QueryType = 2
	QueryType_QUERY_TYPE_COMMUNITY       QueryType = 3
	QueryType_QUERY_TYPE_LARGE_COMMUNITY QueryType = 4
	QueryType_QUERY_TYPE_BGP_SUMMARY     QueryType = 5
	QueryType_QUERY_TYPE_PING            QueryType = 6
	QueryType_QUERY_TYPE_TRACEROUTE      QueryType = 7
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_ROUTE_LOOKUP",
		2: "QUERY_TYPE_AS_PATH",
		3: "QUERY_TYPE_COMMUNITY",
		4: "QUERY_TYPE_LARGE_COMMUNITY",
		5: "QUERY_TYPE_BGP_SUMMARY",
		6: "QUERY_TYPE_PING",
		7: "QUERY_TYPE_TRACEROUTE",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED":     0,
		"QUERY_TYPE_ROUTE_LOOKUP":    1,
		"QUERY_TYPE_AS_PATH":         2,
		"QUERY_TYPE_COMMUNITY":       3,
		"QUERY_TYPE_LARGE_COMMUNITY": 4,
		"QUERY_TYPE_BGP_SUMMARY":     5,
		"QUERY_TYPE_PING":            6,
		"QUERY_TYPE_TRACEROUTE":      7,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_v1_fabric_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_fabric_v1_fabric_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{0}
}

type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_UNSPECIFIED AddressFamily = 0
	AddressFamily_ADDRESS_FAMILY_IPV4        AddressFamily = 1
	AddressFamily_ADDRESS_FAMILY_IPV6        AddressFamily = 2
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ADDRESS_FAMILY_UNSPECIFIED",
		1: "ADDRESS_FAMILY_IPV4",
		2: "ADDRESS_FAMILY_IPV6",
	}
	AddressFamily_value = map[string]int32{
		"ADDRESS_FAMILY_UNSPECIFIED": 0,
		"ADDRESS_FAMILY_IPV4":        1,
		"ADDRESS_FAMILY_IPV6":        2,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_v1_fabric_proto_enumTypes[1].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_fabric_v1_fabric_proto_enumTypes[1]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddressFamily.Descriptor instead.
func (AddressFamily) EnumDescriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{1}
}

type LookupKind int32

const (
	LookupKind_LOOKUP_KIND_UNSPECIFIED LookupKind = 0
	// LOOKUP_KIND_EXACT matched the exact prefix asked for.
	LookupKind_LOOKUP_KIND_EXACT LookupKind = 1
	// LOOKUP_KIND_LONGEST_MATCH matched the most specific prefix covering an
	// address, which may be a default route.
	LookupKind_LOOKUP_KIND_LONGEST_MATCH LookupKind = 2
	// LOOKUP_KIND_SEARCH is an AS-path or community table search.
	LookupKind_LOOKUP_KIND_SEARCH LookupKind = 3
)

// Enum value maps for LookupKind.
var (
	LookupKind_name = map[int32]string{
		0: "LOOKUP_KIND_UNSPECIFIED",
		1: "LOOKUP_KIND_EXACT",
		2: "LOOKUP_KIND_LONGEST_MATCH",
		3: "LOOKUP_KIND_SEARCH",
	}
	LookupKind_value = map[string]int32{
		"LOOKUP_KIND_UNSPECIFIED":   0,
		"LOOKUP_KIND_EXACT":         1,
		"LOOKUP_KIND_LONGEST_MATCH": 2,
		"LOOKUP_KIND_SEARCH":        3,
	}
)

func (x LookupKind) Enum() *LookupKind {
	p := new(LookupKind)
	*p = x
	return p
}

func (x LookupKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookupKind) Descriptor() protoreflect.EnumDescriptor {
	return file_fabric_v1_fabric_proto_enumTypes[2].Descriptor()
}

func (LookupKind) Type() protoreflect.EnumType {
	return &file_fabric_v1_fabric_proto_enumTypes[2]
}

func (x LookupKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookupKind.Descriptor instead.
func (LookupKind) EnumDescriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{2}
}

// Query is a canonical looking-glass query. A probe target is always a
// numeric address by the time it reaches a node.
type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          QueryType              `protobuf:"varint,1,opt,name=type,proto3,enum=fabric.v1.QueryType" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	AddressFamily AddressFamily          `protobuf:"varint,3,opt,name=address_family,json=addressFamily,proto3,enum=fabric.v1.AddressFamily" json:"address_family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetType() QueryType {
	if x != nil {
		return x.Type
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *Query) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Query) GetAddressFamily() AddressFamily {
	if x != nil {
		return x.AddressFamily
	}
	return AddressFamily_ADDRESS_FAMILY_UNSPECIFIED
}

// Budgets bounds one node's result. Zero fields take the node's ceilings.
type Budgets struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MaxResponseBytes      uint32                 `protobuf:"varint,1,opt,name=max_response_bytes,json=maxResponseBytes,proto3" json:"max_response_bytes,omitempty"`
	MaxPrefixes           uint32                 `protobuf:"varint,2,opt,name=max_prefixes,json=maxPrefixes,proto3" json:"max_prefixes,omitempty"`
	MaxPathsPerPrefix     uint32                 `protobuf:"varint,3,opt,name=max_paths_per_prefix,json=maxPathsPerPrefix,proto3" json:"max_paths_per_prefix,omitempty"`
	MaxCommunitiesPerPath uint32                 `protobuf:"varint,4,opt,name=max_communities_per_path,json=maxCommunitiesPerPath,proto3" json:"max_communities_per_path,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Budgets) Reset() {
	*x = Budgets{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budgets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budgets) ProtoMessage() {}

func (x *Budgets) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budgets.ProtoReflect.Descriptor instead.
func (*Budgets) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{1}
}

func (x *Budgets) GetMaxResponseBytes() uint32 {
	if x != nil {
		return x.MaxResponseBytes
	}
	return 0
}

func (x *Budgets) GetMaxPrefixes() uint32 {
	if x != nil {
		return x.MaxPrefixes
	}
	return 0
}

func (x *Budgets) GetMaxPathsPerPrefix() uint32 {
	if x != nil {
		return x.MaxPathsPerPrefix
	}
	return 0
}

func (x *Budgets) GetMaxCommunitiesPerPath() uint32 {
	if x != nil {
		return x.MaxCommunitiesPerPath
	}
	return 0
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id identifies the request across retries; with node and query it
	// is the duplicate-suppression key.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// node is the node the caller expects to reach. A node rejects a request
	// naming another node.
	Node  string `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	Query *Query `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// expires_at is the absolute request expiration. A node rejects an expired
	// request and clamps its own deadline to it.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Budgets       *Budgets               `protobuf:"bytes,5,opt,name=budgets,proto3" json:"budgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ExecuteRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ExecuteRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ExecuteRequest) GetBudgets() *Budgets {
	if x != nil {
		return x.Budgets
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *Observation           `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

// Observation is one node's answer to one query.
type Observation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Node       string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	RouterId   string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Asn        uint32                 `protobuf:"varint,3,opt,name=asn,proto3" json:"asn,omitempty"`
	FrrVersion string                 `protobuf:"bytes,4,opt,name=frr_version,json=frrVersion,proto3" json:"frr_version,omitempty"`
	// sample_time is when the node read FRR or started the probe.
	SampleTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sample_time,json=sampleTime,proto3" json:"sample_time,omitempty"`
	Duration   *durationpb.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// matched counts matching prefixes for a route lookup or search. It is set
	// only when matched_is_exact, i.e. a complete FRR response was parsed.
	Matched        *uint32 `protobuf:"varint,7,opt,name=matched,proto3,oneof" json:"matched,omitempty"`
	MatchedIsExact bool    `protobuf:"varint,8,opt,name=matched_is_exact,json=matchedIsExact,proto3" json:"matched_is_exact,omitempty"`
	// truncated is true when the result was shaped down to budget.
	Truncated bool `protobuf:"varint,9,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*Observation_Routes
	//	*Observation_Summary
	//	*Observation_Ping
	//	*Observation_Traceroute
	Result        isObservation_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Observation) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Observation) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Observation) GetFrrVersion() string {
	if x != nil {
		return x.FrrVersion
	}
	return ""
}

func (x *Observation) GetSampleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SampleTime
	}
	return nil
}

func (x *Observation) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Observation) GetMatched() uint32 {
	if x != nil && x.Matched != nil {
		return *x.Matched
	}
	return 0
}

func (x *Observation) GetMatchedIsExact() bool {
	if x != nil {
		return x.MatchedIsExact
	}
	return false
}

func (x *Observation) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *Observation) GetResult() isObservation_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Observation) GetRoutes() *RouteResult {
	if x != nil {
		if x, ok := x.Result.(*Observation_Routes); ok {
			return x.Routes
		}
	}
	return nil
}

func (x *Observation) GetSummary() *SummaryResult {
	if x != nil {
		if x, ok := x.Result.(*Observation_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *Observation) GetPing() *PingResult {
	if x != nil {
		if x, ok := x.Result.(*Observation_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Observation) GetTraceroute() *TracerouteResult {
	if x != nil {
		if x, ok := x.Result.(*Observation_Traceroute); ok {
			return x.Traceroute
		}
	}
	return nil
}

type isObservation_Result interface {
	isObservation_Result()
}

type Observation_Routes struct {
	Routes *RouteResult `protobuf:"bytes,10,opt,name=routes,proto3,oneof"`
}

type Observation_Summary struct {
	Summary *SummaryResult `protobuf:"bytes,11,opt,name=summary,proto3,oneof"`
}

type Observation_Ping struct {
	Ping *PingResult `protobuf:"bytes,12,opt,name=ping,proto3,oneof"`
}

type Observation_Traceroute struct {
	Traceroute *TracerouteResult `protobuf:"bytes,13,opt,name=traceroute,proto3,oneof"`
}

func (*Observation_Routes) isObservation_Result() {}

func (*Observation_Summary) isObservation_Result() {}

func (*Observation_Ping) isObservation_Result() {}

func (*Observation_Traceroute) isObservation_Result() {}

type RouteResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	LookupKind LookupKind             `protobuf:"varint,1,opt,name=lookup_kind,json=lookupKind,proto3,enum=fabric.v1.LookupKind" json:"lookup_kind,omitempty"`
	Prefixes   []*PrefixObservation   `protobuf:"bytes,2,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	// index is set when a search was answered from the node's search index
	// instead of by FRR: each prefix then carries its selected path only.
	Index         *IndexState `protobuf:"bytes,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResult) Reset() {
	*x = RouteResult{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResult) ProtoMessage() {}

func (x *RouteResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResult.ProtoReflect.Descriptor instead.
func (*RouteResult) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{5}
}

func (x *RouteResult) GetLookupKind() LookupKind {
	if x != nil {
		return x.LookupKind
	}
	return LookupKind_LOOKUP_KIND_UNSPECIFIED
}

func (x *RouteResult) GetPrefixes() []*PrefixObservation {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *RouteResult) GetIndex() *IndexState {
	if x != nil {
		return x.Index
	}
	return nil
}

// IndexState is the freshness of the node's search index, which follows
// bgpd's Loc-RIB over BMP.
type IndexState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// synced_at is when the current BMP session's initial table completed.
	SyncedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`
	// last_update is when the last route change was applied.
	LastUpdate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	// version counts route changes applied; it only grows.
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// routes is the number of prefixes the index holds.
	Routes        uint64 `protobuf:"varint,4,opt,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexState) Reset() {
	*x = IndexState{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexState) ProtoMessage() {}

func (x *IndexState) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexState.ProtoReflect.Descriptor instead.
func (*IndexState) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{6}
}

func (x *IndexState) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

func (x *IndexState) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *IndexState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *IndexState) GetRoutes() uint64 {
	if x != nil {
		return x.Routes
	}
	return 0
}

// PrefixObservation is one prefix as one router holds it.
type PrefixObservation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prefix string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// paths is the router's own paths. best describes that router's BGP choice
	// only.
	Paths      []*Path `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	TotalPaths uint32  `protobuf:"varint,3,opt,name=total_paths,json=totalPaths,proto3" json:"total_paths,omitempty"`
	// installation is zebra's RIB entry for the prefix, sampled separately.
	// Unset for searches.
	Installation  *Installation `protobuf:"bytes,4,opt,name=installation,proto3" json:"installation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefixObservation) Reset() {
	*x = PrefixObservation{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixObservation) ProtoMessage() {}

func (x *PrefixObservation) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixObservation.ProtoReflect.Descriptor instead.
func (*PrefixObservation) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{7}
}

func (x *PrefixObservation) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *PrefixObservation) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *PrefixObservation) GetTotalPaths() uint32 {
	if x != nil {
		return x.TotalPaths
	}
	return 0
}

func (x *PrefixObservation) GetInstallation() *Installation {
	if x != nil {
		return x.Installation
	}
	return nil
}

type Path struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Best            bool                   `protobuf:"varint,1,opt,name=best,proto3" json:"best,omitempty"`
	Multipath       bool                   `protobuf:"varint,2,opt,name=multipath,proto3" json:"multipath,omitempty"`
	Valid           bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	SelectionReason string                 `protobuf:"bytes,4,opt,name=selection_reason,json=selectionReason,proto3" json:"selection_reason,omitempty"`
	AsPath          string                 `protobuf:"bytes,5,opt,name=as_path,json=asPath,proto3" json:"as_path,omitempty"`
	AsPathSegments  []*ASSegment           `protobuf:"bytes,6,rep,name=as_path_segments,json=asPathSegments,proto3" json:"as_path_segments,omitempty"`
	// origin is the BGP ORIGIN attribute (IGP, EGP, incomplete).
	Origin string `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	// origin_asn is the AS that originated the prefix; 0 when local or
	// ambiguous (a trailing AS_SET).
	OriginAsn             uint32                 `protobuf:"varint,8,opt,name=origin_asn,json=originAsn,proto3" json:"origin_asn,omitempty"`
	LocalPref             *uint32                `protobuf:"varint,9,opt,name=local_pref,json=localPref,proto3,oneof" json:"local_pref,omitempty"`
	Med                   *uint32                `protobuf:"varint,10,opt,name=med,proto3,oneof" json:"med,omitempty"`
	Weight                uint32                 `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Local                 bool                   `protobuf:"varint,12,opt,name=local,proto3" json:"local,omitempty"`
	Aggregated            bool                   `protobuf:"varint,13,opt,name=aggregated,proto3" json:"aggregated,omitempty"`
	Communities           []string               `protobuf:"bytes,14,rep,name=communities,proto3" json:"communities,omitempty"`
	TotalCommunities      uint32                 `protobuf:"varint,15,opt,name=total_communities,json=totalCommunities,proto3" json:"total_communities,omitempty"`
	LargeCommunities      []string               `protobuf:"bytes,16,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	TotalLargeCommunities uint32                 `protobuf:"varint,17,opt,name=total_large_communities,json=totalLargeCommunities,proto3" json:"total_large_communities,omitempty"`
	NextHops              []*NextHop             `protobuf:"bytes,18,rep,name=next_hops,json=nextHops,proto3" json:"next_hops,omitempty"`
	PeerAddress           string                 `protobuf:"bytes,19,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	PeerRouterId          string                 `protobuf:"bytes,20,opt,name=peer_router_id,json=peerRouterId,proto3" json:"peer_router_id,omitempty"`
	PeerHostname          string                 `protobuf:"bytes,21,opt,name=peer_hostname,json=peerHostname,proto3" json:"peer_hostname,omitempty"`
	PeerType              string                 `protobuf:"bytes,22,opt,name=peer_type,json=peerType,proto3" json:"peer_type,omitempty"`
	LastUpdate            *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{8}
}

func (x *Path) GetBest() bool {
	if x != nil {
		return x.Best
	}
	return false
}

func (x *Path) GetMultipath() bool {
	if x != nil {
		return x.Multipath
	}
	return false
}

func (x *Path) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *Path) GetSelectionReason() string {
	if x != nil {
		return x.SelectionReason
	}
	return ""
}

func (x *Path) GetAsPath() string {
	if x != nil {
		return x.AsPath
	}
	return ""
}

func (x *Path) GetAsPathSegments() []*ASSegment {
	if x != nil {
		return x.AsPathSegments
	}
	return nil
}

func (x *Path) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Path) GetOriginAsn() uint32 {
	if x != nil {
		return x.OriginAsn
	}
	return 0
}

func (x *Path) GetLocalPref() uint32 {
	if x != nil && x.LocalPref != nil {
		return *x.LocalPref
	}
	return 0
}

func (x *Path) GetMed() uint32 {
	if x != nil && x.Med != nil {
		return *x.Med
	}
	return 0
}

func (x *Path) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Path) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

func (x *Path) GetAggregated() bool {
	if x != nil {
		return x.Aggregated
	}
	return false
}

func (x *Path) GetCommunities() []string {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *Path) GetTotalCommunities() uint32 {
	if x != nil {
		return x.TotalCommunities
	}
	return 0
}

func (x *Path) GetLargeCommunities() []string {
	if x != nil {
		return x.LargeCommunities
	}
	return nil
}

func (x *Path) GetTotalLargeCommunities() uint32 {
	if x != nil {
		return x.TotalLargeCommunities
	}
	return 0
}

func (x *Path) GetNextHops() []*NextHop {
	if x != nil {
		return x.NextHops
	}
	return nil
}

func (x *Path) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

func (x *Path) GetPeerRouterId() string {
	if x != nil {
		return x.PeerRouterId
	}
	return ""
}

func (x *Path) GetPeerHostname() string {
	if x != nil {
		return x.PeerHostname
	}
	return ""
}

func (x *Path) GetPeerType() string {
	if x != nil {
		return x.PeerType
	}
	return ""
}

func (x *Path) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

type ASSegment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is as-sequence, as-set, as-confed-sequence or as-confed-set.
	Type          string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Asns          []uint32 `protobuf:"varint,2,rep,packed,name=asns,proto3" json:"asns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASSegment) Reset() {
	*x = ASSegment{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASSegment) ProtoMessage() {}

func (x *ASSegment) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASSegment.ProtoReflect.Descriptor instead.
func (*ASSegment) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{9}
}

func (x *ASSegment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ASSegment) GetAsns() []uint32 {
	if x != nil {
		return x.Asns
	}
	return nil
}

type NextHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Accessible    bool                   `protobuf:"varint,4,opt,name=accessible,proto3" json:"accessible,omitempty"`
	Used          bool                   `protobuf:"varint,5,opt,name=used,proto3" json:"used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextHop) Reset() {
	*x = NextHop{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextHop) ProtoMessage() {}

func (x *NextHop) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextHop.ProtoReflect.Descriptor instead.
func (*NextHop) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{10}
}

func (x *NextHop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NextHop) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NextHop) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *NextHop) GetAccessible() bool {
	if x != nil {
		return x.Accessible
	}
	return false
}

func (x *NextHop) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

// Installation is zebra's evidence for one prefix, with its own sample time.
// It says nothing about reachability beyond this router or about XDP
// forwarding.
type Installation struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SampleTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sample_time,json=sampleTime,proto3" json:"sample_time,omitempty"`
	Present    bool                   `protobuf:"varint,2,opt,name=present,proto3" json:"present,omitempty"`
	Routes     []*ZebraRoute          `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	// error_code is set when zebra could not be read; the BGP answer stands.
	ErrorCode     string `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Installation) Reset() {
	*x = Installation{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Installation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Installation) ProtoMessage() {}

func (x *Installation) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Installation.ProtoReflect.Descriptor instead.
func (*Installation) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{11}
}

func (x *Installation) GetSampleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SampleTime
	}
	return nil
}

func (x *Installation) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *Installation) GetRoutes() []*ZebraRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *Installation) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Installation) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ZebraRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Selected      bool                   `protobuf:"varint,2,opt,name=selected,proto3" json:"selected,omitempty"`
	Installed     bool                   `protobuf:"varint,3,opt,name=installed,proto3" json:"installed,omitempty"`
	Distance      uint32                 `protobuf:"varint,4,opt,name=distance,proto3" json:"distance,omitempty"`
	Metric        uint32                 `protobuf:"varint,5,opt,name=metric,proto3" json:"metric,omitempty"`
	NextHops      []*ZebraNextHop        `protobuf:"bytes,6,rep,name=next_hops,json=nextHops,proto3" json:"next_hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZebraRoute) Reset() {
	*x = ZebraRoute{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZebraRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZebraRoute) ProtoMessage() {}

func (x *ZebraRoute) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZebraRoute.ProtoReflect.Descriptor instead.
func (*ZebraRoute) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{12}
}

func (x *ZebraRoute) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ZebraRoute) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *ZebraRoute) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *ZebraRoute) GetDistance() uint32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *ZebraRoute) GetMetric() uint32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *ZebraRoute) GetNextHops() []*ZebraNextHop {
	if x != nil {
		return x.NextHops
	}
	return nil
}

type ZebraNextHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Interface     string                 `protobuf:"bytes,2,opt,name=interface,proto3" json:"interface,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Fib           bool                   `protobuf:"varint,4,opt,name=fib,proto3" json:"fib,omitempty"`
	Blackhole     bool                   `protobuf:"varint,5,opt,name=blackhole,proto3" json:"blackhole,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZebraNextHop) Reset() {
	*x = ZebraNextHop{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZebraNextHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZebraNextHop) ProtoMessage() {}

func (x *ZebraNextHop) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZebraNextHop.ProtoReflect.Descriptor instead.
func (*ZebraNextHop) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{13}
}

func (x *ZebraNextHop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ZebraNextHop) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *ZebraNextHop) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *ZebraNextHop) GetFib() bool {
	if x != nil {
		return x.Fib
	}
	return false
}

func (x *ZebraNextHop) GetBlackhole() bool {
	if x != nil {
		return x.Blackhole
	}
	return false
}

type SummaryResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RouterId         string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Asn              uint32                 `protobuf:"varint,2,opt,name=asn,proto3" json:"asn,omitempty"`
	Peers            []*Peer                `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	TotalPeers       uint32                 `protobuf:"varint,4,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	EstablishedPeers uint32                 `protobuf:"varint,5,opt,name=established_peers,json=establishedPeers,proto3" json:"established_peers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SummaryResult) Reset() {
	*x = SummaryResult{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResult) ProtoMessage() {}

func (x *SummaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResult.ProtoReflect.Descriptor instead.
func (*SummaryResult) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{14}
}

func (x *SummaryResult) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *SummaryResult) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *SummaryResult) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *SummaryResult) GetTotalPeers() uint32 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

func (x *SummaryResult) GetEstablishedPeers() uint32 {
	if x != nil {
		return x.EstablishedPeers
	}
	return 0
}

// Peer is one BGP session. A session that is down is data, not a failure.
type Peer struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Address                string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Hostname               string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Description            string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RemoteAs               uint32                 `protobuf:"varint,4,opt,name=remote_as,json=remoteAs,proto3" json:"remote_as,omitempty"`
	LocalAs                uint32                 `protobuf:"varint,5,opt,name=local_as,json=localAs,proto3" json:"local_as,omitempty"`
	State                  string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Established            bool                   `protobuf:"varint,7,opt,name=established,proto3" json:"established,omitempty"`
	Uptime                 *durationpb.Duration   `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	PrefixesReceived       uint32                 `protobuf:"varint,9,opt,name=prefixes_received,json=prefixesReceived,proto3" json:"prefixes_received,omitempty"`
	PrefixesSent           uint32                 `protobuf:"varint,10,opt,name=prefixes_sent,json=prefixesSent,proto3" json:"prefixes_sent,omitempty"`
	MessagesReceived       uint64                 `protobuf:"varint,11,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	MessagesSent           uint64                 `protobuf:"varint,12,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	ConnectionsEstablished uint32                 `protobuf:"varint,13,opt,name=connections_established,json=connectionsEstablished,proto3" json:"connections_established,omitempty"`
	ConnectionsDropped     uint32                 `protobuf:"varint,14,opt,name=connections_dropped,json=connectionsDropped,proto3" json:"connections_dropped,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{15}
}

func (x *Peer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Peer) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Peer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Peer) GetRemoteAs() uint32 {
	if x != nil {
		return x.RemoteAs
	}
	return 0
}

func (x *Peer) GetLocalAs() uint32 {
	if x != nil {
		return x.LocalAs
	}
	return 0
}

func (x *Peer) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Peer) GetEstablished() bool {
	if x != nil {
		return x.Established
	}
	return false
}

func (x *Peer) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *Peer) GetPrefixesReceived() uint32 {
	if x != nil {
		return x.PrefixesReceived
	}
	return 0
}

func (x *Peer) GetPrefixesSent() uint32 {
	if x != nil {
		return x.PrefixesSent
	}
	return 0
}

func (x *Peer) GetMessagesReceived() uint64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *Peer) GetMessagesSent() uint64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *Peer) GetConnectionsEstablished() uint32 {
	if x != nil {
		return x.ConnectionsEstablished
	}
	return 0
}

func (x *Peer) GetConnectionsDropped() uint32 {
	if x != nil {
		return x.ConnectionsDropped
	}
	return 0
}

type PingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Sent          uint32                 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Received      uint32                 `protobuf:"varint,4,opt,name=received,proto3" json:"received,omitempty"`
	Replies       []*ProbeReply          `protobuf:"bytes,5,rep,name=replies,proto3" json:"replies,omitempty"`
	RttMin        *durationpb.Duration   `protobuf:"bytes,6,opt,name=rtt_min,json=rttMin,proto3" json:"rtt_min,omitempty"`
	RttAvg        *durationpb.Duration   `protobuf:"bytes,7,opt,name=rtt_avg,json=rttAvg,proto3" json:"rtt_avg,omitempty"`
	RttMax        *durationpb.Duration   `protobuf:"bytes,8,opt,name=rtt_max,json=rttMax,proto3" json:"rtt_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{16}
}

func (x *PingResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PingResult) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *PingResult) GetSent() uint32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *PingResult) GetReceived() uint32 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *PingResult) GetReplies() []*ProbeReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *PingResult) GetRttMin() *durationpb.Duration {
	if x != nil {
		return x.RttMin
	}
	return nil
}

func (x *PingResult) GetRttAvg() *durationpb.Duration {
	if x != nil {
		return x.RttAvg
	}
	return nil
}

func (x *PingResult) GetRttMax() *durationpb.Duration {
	if x != nil {
		return x.RttMax
	}
	return nil
}

type TracerouteResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Source      string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// reached is true when the destination answered.
	Reached       bool   `protobuf:"varint,3,opt,name=reached,proto3" json:"reached,omitempty"`
	Hops          []*Hop `protobuf:"bytes,4,rep,name=hops,proto3" json:"hops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteResult) Reset() {
	*x = TracerouteResult{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteResult) ProtoMessage() {}

func (x *TracerouteResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteResult.ProtoReflect.Descriptor instead.
func (*TracerouteResult) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{17}
}

func (x *TracerouteResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TracerouteResult) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TracerouteResult) GetReached() bool {
	if x != nil {
		return x.Reached
	}
	return false
}

func (x *TracerouteResult) GetHops() []*Hop {
	if x != nil {
		return x.Hops
	}
	return nil
}

type Hop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           uint32                 `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Probes        []*ProbeReply          `protobuf:"bytes,2,rep,name=probes,proto3" json:"probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hop) Reset() {
	*x = Hop{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hop) ProtoMessage() {}

func (x *Hop) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hop.ProtoReflect.Descriptor instead.
func (*Hop) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{18}
}

func (x *Hop) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Hop) GetProbes() []*ProbeReply {
	if x != nil {
		return x.Probes
	}
	return nil
}

// ProbeReply is the outcome of one probe packet. A probe with no reply is
// diagnostic data.
type ProbeReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// address is the replying router or host; empty on timeout.
	Address string               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Rtt     *durationpb.Duration `protobuf:"bytes,3,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Timeout bool                 `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// icmp_type is the reply's type: echo-reply, time-exceeded,
	// destination-unreachable, packet-too-big or parameter-problem.
	IcmpType      string `protobuf:"bytes,5,opt,name=icmp_type,json=icmpType,proto3" json:"icmp_type,omitempty"`
	IcmpCode      uint32 `protobuf:"varint,6,opt,name=icmp_code,json=icmpCode,proto3" json:"icmp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeReply) Reset() {
	*x = ProbeReply{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReply) ProtoMessage() {}

func (x *ProbeReply) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReply.ProtoReflect.Descriptor instead.
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{19}
}

func (x *ProbeReply) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ProbeReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ProbeReply) GetRtt() *durationpb.Duration {
	if x != nil {
		return x.Rtt
	}
	return nil
}

func (x *ProbeReply) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

func (x *ProbeReply) GetIcmpType() string {
	if x != nil {
		return x.IcmpType
	}
	return ""
}

func (x *ProbeReply) GetIcmpCode() uint32 {
	if x != nil {
		return x.IcmpCode
	}
	return 0
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{20}
}

type InfoResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Node       string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Site       string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	RouterId   string                 `protobuf:"bytes,3,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Asn        uint32                 `protobuf:"varint,4,opt,name=asn,proto3" json:"asn,omitempty"`
	FrrVersion string                 `protobuf:"bytes,5,opt,name=frr_version,json=frrVersion,proto3" json:"frr_version,omitempty"`
	// diagnostics_available is false while FRR is unreachable, its version is
	// unsupported, or credentials are missing; unavailable_reason says which.
	DiagnosticsAvailable bool        `protobuf:"varint,6,opt,name=diagnostics_available,json=diagnosticsAvailable,proto3" json:"diagnostics_available,omitempty"`
	UnavailableReason    string      `protobuf:"bytes,7,opt,name=unavailable_reason,json=unavailableReason,proto3" json:"unavailable_reason,omitempty"`
	EnabledQueryTypes    []QueryType `protobuf:"varint,8,rep,packed,name=enabled_query_types,json=enabledQueryTypes,proto3,enum=fabric.v1.QueryType" json:"enabled_query_types,omitempty"`
	// probe_sources lists the per-family probe source addresses that are
	// available.
	ProbeSources  []string `protobuf:"bytes,9,rep,name=probe_sources,json=probeSources,proto3" json:"probe_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{21}
}

func (x *InfoResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *InfoResponse) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *InfoResponse) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *InfoResponse) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *InfoResponse) GetFrrVersion() string {
	if x != nil {
		return x.FrrVersion
	}
	return ""
}

func (x *InfoResponse) GetDiagnosticsAvailable() bool {
	if x != nil {
		return x.DiagnosticsAvailable
	}
	return false
}

func (x *InfoResponse) GetUnavailableReason() string {
	if x != nil {
		return x.UnavailableReason
	}
	return ""
}

func (x *InfoResponse) GetEnabledQueryTypes() []QueryType {
	if x != nil {
		return x.EnabledQueryTypes
	}
	return nil
}

func (x *InfoResponse) GetProbeSources() []string {
	if x != nil {
		return x.ProbeSources
	}
	return nil
}

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// nodes restricts execution to these node names; empty means every
	// eligible node.
	Nodes   []string `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Budgets *Budgets `protobuf:"bytes,3,opt,name=budgets,proto3" json:"budgets,omitempty"`
	// timeout bounds the whole query; it is clamped to the gateway's ceiling.
	Timeout       *durationpb.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{22}
}

func (x *QueryRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *QueryRequest) GetBudgets() *Budgets {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *QueryRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Results       []*NodeResult          `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{23}
}

func (x *QueryResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryResponse) GetResults() []*NodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type NodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Observation   *Observation           `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResult) Reset() {
	*x = NodeResult{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResult) ProtoMessage() {}

func (x *NodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResult.ProtoReflect.Descriptor instead.
func (*NodeResult) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{24}
}

func (x *NodeResult) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeResult) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *NodeResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *NodeResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{25}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeEndpoint        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{26}
}

func (x *ListNodesResponse) GetNodes() []*NodeEndpoint {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Pod           string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	PodUid        string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	HostIp        string                 `protobuf:"bytes,4,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	Ready         bool                   `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEndpoint) Reset() {
	*x = NodeEndpoint{}
	mi := &file_fabric_v1_fabric_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEndpoint) ProtoMessage() {}

func (x *NodeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_fabric_v1_fabric_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEndpoint.ProtoReflect.Descriptor instead.
func (*NodeEndpoint) Descriptor() ([]byte, []int) {
	return file_fabric_v1_fabric_proto_rawDescGZIP(), []int{27}
}

func (x *NodeEndpoint) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *NodeEndpoint) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *NodeEndpoint) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *NodeEndpoint) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *NodeEndpoint) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

var File_fabric_v1_fabric_proto protoreflect.FileDescriptor

const file_fabric_v1_fabric_proto_rawDesc = "" +
	"\n" +
	"\x16fabric/v1/fabric.proto\x12\tfabric.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x05Query\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.fabric.v1.QueryTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12?\n" +
	"\x0eaddress_family\x18\x03 \x01(\x0e2\x18.fabric.v1.AddressFamilyR\raddressFamily\"\xc4\x01\n" +
	"\aBudgets\x12,\n" +
	"\x12max_response_bytes\x18\x01 \x01(\rR\x10maxResponseBytes\x12!\n" +
	"\fmax_prefixes\x18\x02 \x01(\rR\vmaxPrefixes\x12/\n" +
	"\x14max_paths_per_prefix\x18\x03 \x01(\rR\x11maxPathsPerPrefix\x127\n" +
	"\x18max_communities_per_path\x18\x04 \x01(\rR\x15maxCommunitiesPerPath\"\xd4\x01\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x12&\n" +
	"\x05query\x18\x03 \x01(\v2\x10.fabric.v1.QueryR\x05query\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12,\n" +
	"\abudgets\x18\x05 \x01(\v2\x12.fabric.v1.BudgetsR\abudgets\"K\n" +
	"\x0fExecuteResponse\x128\n" +
	"\vobservation\x18\x01 \x01(\v2\x16.fabric.v1.ObservationR\vobservation\"\xb6\x04\n" +
	"\vObservation\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x12\x10\n" +
	"\x03asn\x18\x03 \x01(\rR\x03asn\x12\x1f\n" +
	"\vfrr_version\x18\x04 \x01(\tR\n" +
	"frrVersion\x12;\n" +
	"\vsample_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sampleTime\x125\n" +
	"\bduration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1d\n" +
	"\amatched\x18\a \x01(\rH\x01R\amatched\x88\x01\x01\x12(\n" +
	"\x10matched_is_exact\x18\b \x01(\bR\x0ematchedIsExact\x12\x1c\n" +
	"\ttruncated\x18\t \x01(\bR\ttruncated\x120\n" +
	"\x06routes\x18\n" +
	" \x01(\v2\x16.fabric.v1.RouteResultH\x00R\x06routes\x124\n" +
	"\asummary\x18\v \x01(\v2\x18.fabric.v1.SummaryResultH\x00R\asummary\x12+\n" +
	"\x04ping\x18\f \x01(\v2\x15.fabric.v1.PingResultH\x00R\x04ping\x12=\n" +
	"\n" +
	"traceroute\x18\r \x01(\v2\x1b.fabric.v1.TracerouteResultH\x00R\n" +
	"tracerouteB\b\n" +
	"\x06resultB\n" +
	"\n" +
	"\b_matched\"\xac\x01\n" +
	"\vRouteResult\x126\n" +
	"\vlookup_kind\x18\x01 \x01(\x0e2\x15.fabric.v1.LookupKindR\n" +
	"lookupKind\x128\n" +
	"\bprefixes\x18\x02 \x03(\v2\x1c.fabric.v1.PrefixObservationR\bprefixes\x12+\n" +
	"\x05index\x18\x03 \x01(\v2\x15.fabric.v1.IndexStateR\x05index\"\xb4\x01\n" +
	"\n" +
	"IndexState\x127\n" +
	"\tsynced_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt\x12;\n" +
	"\vlast_update\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x16\n" +
	"\x06routes\x18\x04 \x01(\x04R\x06routes\"\xb0\x01\n" +
	"\x11PrefixObservation\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12%\n" +
	"\x05paths\x18\x02 \x03(\v2\x0f.fabric.v1.PathR\x05paths\x12\x1f\n" +
	"\vtotal_paths\x18\x03 \x01(\rR\n" +
	"totalPaths\x12;\n" +
	"\finstallation\x18\x04 \x01(\v2\x17.fabric.v1.InstallationR\finstallation\"\xd6\x06\n" +
	"\x04Path\x12\x12\n" +
	"\x04best\x18\x01 \x01(\bR\x04best\x12\x1c\n" +
	"\tmultipath\x18\x02 \x01(\bR\tmultipath\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\x12)\n" +
	"\x10selection_reason\x18\x04 \x01(\tR\x0fselectionReason\x12\x17\n" +
	"\aas_path\x18\x05 \x01(\tR\x06asPath\x12>\n" +
	"\x10as_path_segments\x18\x06 \x03(\v2\x14.fabric.v1.ASSegmentR\x0easPathSegments\x12\x16\n" +
	"\x06origin\x18\a \x01(\tR\x06origin\x12\x1d\n" +
	"\n" +
	"origin_asn\x18\b \x01(\rR\toriginAsn\x12\"\n" +
	"\n" +
	"local_pref\x18\t \x01(\rH\x00R\tlocalPref\x88\x01\x01\x12\x15\n" +
	"\x03med\x18\n" +
	" \x01(\rH\x01R\x03med\x88\x01\x01\x12\x16\n" +
	"\x06weight\x18\v \x01(\rR\x06weight\x12\x14\n" +
	"\x05local\x18\f \x01(\bR\x05local\x12\x1e\n" +
	"\n" +
	"aggregated\x18\r \x01(\bR\n" +
	"aggregated\x12 \n" +
	"\vcommunities\x18\x0e \x03(\tR\vcommunities\x12+\n" +
	"\x11total_communities\x18\x0f \x01(\rR\x10totalCommunities\x12+\n" +
	"\x11large_communities\x18\x10 \x03(\tR\x10largeCommunities\x126\n" +
	"\x17total_large_communities\x18\x11 \x01(\rR\x15totalLargeCommunities\x12/\n" +
	"\tnext_hops\x18\x12 \x03(\v2\x12.fabric.v1.NextHopR\bnextHops\x12!\n" +
	"\fpeer_address\x18\x13 \x01(\tR\vpeerAddress\x12$\n" +
	"\x0epeer_router_id\x18\x14 \x01(\tR\fpeerRouterId\x12#\n" +
	"\rpeer_hostname\x18\x15 \x01(\tR\fpeerHostname\x12\x1b\n" +
	"\tpeer_type\x18\x16 \x01(\tR\bpeerType\x12;\n" +
	"\vlast_update\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdateB\r\n" +
	"\v_local_prefB\x06\n" +
	"\x04_med\"3\n" +
	"\tASSegment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04asns\x18\x02 \x03(\rR\x04asns\"\x89\x01\n" +
	"\aNextHop\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x1e\n" +
	"\n" +
	"accessible\x18\x04 \x01(\bR\n" +
	"accessible\x12\x12\n" +
	"\x04used\x18\x05 \x01(\bR\x04used\"\xd8\x01\n" +
	"\fInstallation\x12;\n" +
	"\vsample_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"sampleTime\x12\x18\n" +
	"\apresent\x18\x02 \x01(\bR\apresent\x12-\n" +
	"\x06routes\x18\x03 \x03(\v2\x15.fabric.v1.ZebraRouteR\x06routes\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xcc\x01\n" +
	"\n" +
	"ZebraRoute\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1a\n" +
	"\bselected\x18\x02 \x01(\bR\bselected\x12\x1c\n" +
	"\tinstalled\x18\x03 \x01(\bR\tinstalled\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\rR\bdistance\x12\x16\n" +
	"\x06metric\x18\x05 \x01(\rR\x06metric\x124\n" +
	"\tnext_hops\x18\x06 \x03(\v2\x17.fabric.v1.ZebraNextHopR\bnextHops\"\x8e\x01\n" +
	"\fZebraNextHop\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1c\n" +
	"\tinterface\x18\x02 \x01(\tR\tinterface\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x10\n" +
	"\x03fib\x18\x04 \x01(\bR\x03fib\x12\x1c\n" +
	"\tblackhole\x18\x05 \x01(\bR\tblackhole\"\xb3\x01\n" +
	"\rSummaryResult\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12\x10\n" +
	"\x03asn\x18\x02 \x01(\rR\x03asn\x12%\n" +
	"\x05peers\x18\x03 \x03(\v2\x0f.fabric.v1.PeerR\x05peers\x12\x1f\n" +
	"\vtotal_peers\x18\x04 \x01(\rR\n" +
	"totalPeers\x12+\n" +
	"\x11established_peers\x18\x05 \x01(\rR\x10establishedPeers\"\x8f\x04\n" +
	"\x04Peer\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tremote_as\x18\x04 \x01(\rR\bremoteAs\x12\x19\n" +
	"\blocal_as\x18\x05 \x01(\rR\alocalAs\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12 \n" +
	"\vestablished\x18\a \x01(\bR\vestablished\x121\n" +
	"\x06uptime\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12+\n" +
	"\x11prefixes_received\x18\t \x01(\rR\x10prefixesReceived\x12#\n" +
	"\rprefixes_sent\x18\n" +
	" \x01(\rR\fprefixesSent\x12+\n" +
	"\x11messages_received\x18\v \x01(\x04R\x10messagesReceived\x12#\n" +
	"\rmessages_sent\x18\f \x01(\x04R\fmessagesSent\x127\n" +
	"\x17connections_established\x18\r \x01(\rR\x16connectionsEstablished\x12/\n" +
	"\x13connections_dropped\x18\x0e \x01(\rR\x12connectionsDropped\"\xc3\x02\n" +
	"\n" +
	"PingResult\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\rR\x04sent\x12\x1a\n" +
	"\breceived\x18\x04 \x01(\rR\breceived\x12/\n" +
	"\areplies\x18\x05 \x03(\v2\x15.fabric.v1.ProbeReplyR\areplies\x122\n" +
	"\artt_min\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x06rttMin\x122\n" +
	"\artt_avg\x18\a \x01(\v2\x19.google.protobuf.DurationR\x06rttAvg\x122\n" +
	"\artt_max\x18\b \x01(\v2\x19.google.protobuf.DurationR\x06rttMax\"\x8a\x01\n" +
	"\x10TracerouteResult\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x18\n" +
	"\areached\x18\x03 \x01(\bR\areached\x12\"\n" +
	"\x04hops\x18\x04 \x03(\v2\x0e.fabric.v1.HopR\x04hops\"F\n" +
	"\x03Hop\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\rR\x03ttl\x12-\n" +
	"\x06probes\x18\x02 \x03(\v2\x15.fabric.v1.ProbeReplyR\x06probes\"\xc3\x01\n" +
	"\n" +
	"ProbeReply\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12+\n" +
	"\x03rtt\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x03rtt\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\bR\atimeout\x12\x1b\n" +
	"\ticmp_type\x18\x05 \x01(\tR\bicmpType\x12\x1b\n" +
	"\ticmp_code\x18\x06 \x01(\rR\bicmpCode\"\r\n" +
	"\vInfoRequest\"\xd5\x02\n" +
	"\fInfoResponse\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x1b\n" +
	"\trouter_id\x18\x03 \x01(\tR\brouterId\x12\x10\n" +
	"\x03asn\x18\x04 \x01(\rR\x03asn\x12\x1f\n" +
	"\vfrr_version\x18\x05 \x01(\tR\n" +
	"frrVersion\x123\n" +
	"\x15diagnostics_available\x18\x06 \x01(\bR\x14diagnosticsAvailable\x12-\n" +
	"\x12unavailable_reason\x18\a \x01(\tR\x11unavailableReason\x12D\n" +
	"\x13enabled_query_types\x18\b \x03(\x0e2\x14.fabric.v1.QueryTypeR\x11enabledQueryTypes\x12#\n" +
	"\rprobe_sources\x18\t \x03(\tR\fprobeSources\"\xaf\x01\n" +
	"\fQueryRequest\x12&\n" +
	"\x05query\x18\x01 \x01(\v2\x10.fabric.v1.QueryR\x05query\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x12,\n" +
	"\abudgets\x18\x03 \x01(\v2\x12.fabric.v1.BudgetsR\abudgets\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"_\n" +
	"\rQueryResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12/\n" +
	"\aresults\x18\x02 \x03(\v2\x15.fabric.v1.NodeResultR\aresults\"\x9e\x01\n" +
	"\n" +
	"NodeResult\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x128\n" +
	"\vobservation\x18\x02 \x01(\v2\x16.fabric.v1.ObservationR\vobservation\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x12\n" +
	"\x10ListNodesRequest\"B\n" +
	"\x11ListNodesResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.fabric.v1.NodeEndpointR\x05nodes\"|\n" +
	"\fNodeEndpoint\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x17\n" +
	"\ahost_ip\x18\x04 \x01(\tR\x06hostIp\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\bR\x05ready*\xe2\x01\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17QUERY_TYPE_ROUTE_LOOKUP\x10\x01\x12\x16\n" +
	"\x12QUERY_TYPE_AS_PATH\x10\x02\x12\x18\n" +
	"\x14QUERY_TYPE_COMMUNITY\x10\x03\x12\x1e\n" +
	"\x1aQUERY_TYPE_LARGE_COMMUNITY\x10\x04\x12\x1a\n" +
	"\x16QUERY_TYPE_BGP_SUMMARY\x10\x05\x12\x13\n" +
	"\x0fQUERY_TYPE_PING\x10\x06\x12\x19\n" +
	"\x15QUERY_TYPE_TRACEROUTE\x10\a*a\n" +
	"\rAddressFamily\x12\x1e\n" +
	"\x1aADDRESS_FAMILY_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ADDRESS_FAMILY_IPV4\x10\x01\x12\x17\n" +
	"\x13ADDRESS_FAMILY_IPV6\x10\x02*w\n" +
	"\n" +
	"LookupKind\x12\x1b\n" +
	"\x17LOOKUP_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOOKUP_KIND_EXACT\x10\x01\x12\x1d\n" +
	"\x19LOOKUP_KIND_LONGEST_MATCH\x10\x02\x12\x16\n" +
	"\x12LOOKUP_KIND_SEARCH\x10\x032\x8a\x01\n" +
	"\rFabricService\x12@\n" +
	"\aExecute\x12\x19.fabric.v1.ExecuteRequest\x1a\x1a.fabric.v1.ExecuteResponse\x127\n" +
	"\x04Info\x12\x16.fabric.v1.InfoRequest\x1a\x17.fabric.v1.InfoResponse2\x9a\x01\n" +
	"\x14FabricGatewayService\x12:\n" +
	"\x05Query\x12\x17.fabric.v1.QueryRequest\x1a\x18.fabric.v1.QueryResponse\x12F\n" +
	"\tListNodes\x12\x1b.fabric.v1.ListNodesRequest\x1a\x1c.fabric.v1.ListNodesResponseB.Z,go.datum.net/galactic/api/fabric/v1;fabricv1b\x06proto3"

var (
	file_fabric_v1_fabric_proto_rawDescOnce sync.Once
	file_fabric_v1_fabric_proto_rawDescData []byte
)

func file_fabric_v1_fabric_proto_rawDescGZIP() []byte {
	file_fabric_v1_fabric_proto_rawDescOnce.Do(func() {
		file_fabric_v1_fabric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fabric_v1_fabric_proto_rawDesc), len(file_fabric_v1_fabric_proto_rawDesc)))
	})
	return file_fabric_v1_fabric_proto_rawDescData
}

var file_fabric_v1_fabric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fabric_v1_fabric_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_fabric_v1_fabric_proto_goTypes = []any{
	(QueryType)(0),                // 0: fabric.v1.QueryType
	(AddressFamily)(0),            // 1: fabric.v1.AddressFamily
	(LookupKind)(0),               // 2: fabric.v1.LookupKind
	(*Query)(nil),                 // 3: fabric.v1.Query
	(*Budgets)(nil),               // 4: fabric.v1.Budgets
	(*ExecuteRequest)(nil),        // 5: fabric.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 6: fabric.v1.ExecuteResponse
	(*Observation)(nil),           // 7: fabric.v1.Observation
	(*RouteResult)(nil),           // 8: fabric.v1.RouteResult
	(*IndexState)(nil),            // 9: fabric.v1.IndexState
	(*PrefixObservation)(nil),     // 10: fabric.v1.PrefixObservation
	(*Path)(nil),                  // 11: fabric.v1.Path
	(*ASSegment)(nil),             // 12: fabric.v1.ASSegment
	(*NextHop)(nil),               // 13: fabric.v1.NextHop
	(*Installation)(nil),          // 14: fabric.v1.Installation
	(*ZebraRoute)(nil),            // 15: fabric.v1.ZebraRoute
	(*ZebraNextHop)(nil),          // 16: fabric.v1.ZebraNextHop
	(*SummaryResult)(nil),         // 17: fabric.v1.SummaryResult
	(*Peer)(nil),                  // 18: fabric.v1.Peer
	(*PingResult)(nil),            // 19: fabric.v1.PingResult
	(*TracerouteResult)(nil),      // 20: fabric.v1.TracerouteResult
	(*Hop)(nil),                   // 21: fabric.v1.Hop
	(*ProbeReply)(nil),            // 22: fabric.v1.ProbeReply
	(*InfoRequest)(nil),           // 23: fabric.v1.InfoRequest
	(*InfoResponse)(nil),          // 24: fabric.v1.InfoResponse
	(*QueryRequest)(nil),          // 25: fabric.v1.QueryRequest
	(*QueryResponse)(nil),         // 26: fabric.v1.QueryResponse
	(*NodeResult)(nil),            // 27: fabric.v1.NodeResult
	(*ListNodesRequest)(nil),      // 28: fabric.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 29: fabric.v1.ListNodesResponse
	(*NodeEndpoint)(nil),          // 30: fabric.v1.NodeEndpoint
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 32: google.protobuf.Duration
}
var file_fabric_v1_fabric_proto_depIdxs = []int32{
	0,  // 0: fabric.v1.Query.type:type_name -> fabric.v1.QueryType
	1,  // 1: fabric.v1.Query.address_family:type_name -> fabric.v1.AddressFamily
	3,  // 2: fabric.v1.ExecuteRequest.query:type_name -> fabric.v1.Query
	31, // 3: fabric.v1.ExecuteRequest.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 4: fabric.v1.ExecuteRequest.budgets:type_name -> fabric.v1.Budgets
	7,  // 5: fabric.v1.ExecuteResponse.observation:type_name -> fabric.v1.Observation
	31, // 6: fabric.v1.Observation.sample_time:type_name -> google.protobuf.Timestamp
	32, // 7: fabric.v1.Observation.duration:type_name -> google.protobuf.Duration
	8,  // 8: fabric.v1.Observation.routes:type_name -> fabric.v1.RouteResult
	17, // 9: fabric.v1.Observation.summary:type_name -> fabric.v1.SummaryResult
	19, // 10: fabric.v1.Observation.ping:type_name -> fabric.v1.PingResult
	20, // 11: fabric.v1.Observation.traceroute:type_name -> fabric.v1.TracerouteResult
	2,  // 12: fabric.v1.RouteResult.lookup_kind:type_name -> fabric.v1.LookupKind
	10, // 13: fabric.v1.RouteResult.prefixes:type_name -> fabric.v1.PrefixObservation
	9,  // 14: fabric.v1.RouteResult.index:type_name -> fabric.v1.IndexState
	31, // 15: fabric.v1.IndexState.synced_at:type_name -> google.protobuf.Timestamp
	31, // 16: fabric.v1.IndexState.last_update:type_name -> google.protobuf.Timestamp
	11, // 17: fabric.v1.PrefixObservation.paths:type_name -> fabric.v1.Path
	14, // 18: fabric.v1.PrefixObservation.installation:type_name -> fabric.v1.Installation
	12, // 19: fabric.v1.Path.as_path_segments:type_name -> fabric.v1.ASSegment
	13, // 20: fabric.v1.Path.next_hops:type_name -> fabric.v1.NextHop
	31, // 21: fabric.v1.Path.last_update:type_name -> google.protobuf.Timestamp
	31, // 22: fabric.v1.Installation.sample_time:type_name -> google.protobuf.Timestamp
	15, // 23: fabric.v1.Installation.routes:type_name -> fabric.v1.ZebraRoute
	16, // 24: fabric.v1.ZebraRoute.next_hops:type_name -> fabric.v1.ZebraNextHop
	18, // 25: fabric.v1.SummaryResult.peers:type_name -> fabric.v1.Peer
	32, // 26: fabric.v1.Peer.uptime:type_name -> google.protobuf.Duration
	22, // 27: fabric.v1.PingResult.replies:type_name -> fabric.v1.ProbeReply
	32, // 28: fabric.v1.PingResult.rtt_min:type_name -> google.protobuf.Duration
	32, // 29: fabric.v1.PingResult.rtt_avg:type_name -> google.protobuf.Duration
	32, // 30: fabric.v1.PingResult.rtt_max:type_name -> google.protobuf.Duration
	21, // 31: fabric.v1.TracerouteResult.hops:type_name -> fabric.v1.Hop
	22, // 32: fabric.v1.Hop.probes:type_name -> fabric.v1.ProbeReply
	32, // 33: fabric.v1.ProbeReply.rtt:type_name -> google.protobuf.Duration
	0,  // 34: fabric.v1.InfoResponse.enabled_query_types:type_name -> fabric.v1.QueryType
	3,  // 35: fabric.v1.QueryRequest.query:type_name -> fabric.v1.Query
	4,  // 36: fabric.v1.QueryRequest.budgets:type_name -> fabric.v1.Budgets
	32, // 37: fabric.v1.QueryRequest.timeout:type_name -> google.protobuf.Duration
	27, // 38: fabric.v1.QueryResponse.results:type_name -> fabric.v1.NodeResult
	7,  // 39: fabric.v1.NodeResult.observation:type_name -> fabric.v1.Observation
	30, // 40: fabric.v1.ListNodesResponse.nodes:type_name -> fabric.v1.NodeEndpoint
	5,  // 41: fabric.v1.FabricService.Execute:input_type -> fabric.v1.ExecuteRequest
	23, // 42: fabric.v1.FabricService.Info:input_type -> fabric.v1.InfoRequest
	25, // 43: fabric.v1.FabricGatewayService.Query:input_type -> fabric.v1.QueryRequest
	28, // 44: fabric.v1.FabricGatewayService.ListNodes:input_type -> fabric.v1.ListNodesRequest
	6,  // 45: fabric.v1.FabricService.Execute:output_type -> fabric.v1.ExecuteResponse
	24, // 46: fabric.v1.FabricService.Info:output_type -> fabric.v1.InfoResponse
	26, // 47: fabric.v1.FabricGatewayService.Query:output_type -> fabric.v1.QueryResponse
	29, // 48: fabric.v1.FabricGatewayService.ListNodes:output_type -> fabric.v1.ListNodesResponse
	45, // [45:49] is the sub-list for method output_type
	41, // [41:45] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_fabric_v1_fabric_proto_init() }
func file_fabric_v1_fabric_proto_init() {
	if File_fabric_v1_fabric_proto != nil {
		return
	}
	file_fabric_v1_fabric_proto_msgTypes[4].OneofWrappers = []any{
		(*Observation_Routes)(nil),
		(*Observation_Summary)(nil),
		(*Observation_Ping)(nil),
		(*Observation_Traceroute)(nil),
	}
	file_fabric_v1_fabric_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fabric_v1_fabric_proto_rawDesc), len(file_fabric_v1_fabric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fabric_v1_fabric_proto_goTypes,
		DependencyIndexes: file_fabric_v1_fabric_proto_depIdxs,
		EnumInfos:         file_fabric_v1_fabric_proto_enumTypes,
		MessageInfos:      file_fabric_v1_fabric_proto_msgTypes,
	}.Build()
	File_fabric_v1_fabric_proto = out.File
	file_fabric_v1_fabric_proto_goTypes = nil
	file_fabric_v1_fabric_proto_depIdxs = nil
}
