apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fabric-api-gateway
  namespace: galactic-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fabric-api-gateway
