apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fabric
spec:
  template:
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
        - key: galactic.datum.net/node
          value: control
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: galactic.datum.net/node
                    operator: In
                    values:
                      - control
