// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package prog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type UsidFunctionValue struct {
	_        structs.HostLayout
	Behavior uint32
}

type UsidLocatorValue struct {
	_          structs.HostLayout
	Generation uint64
}

type UsidVrfValue struct {
	_              structs.HostLayout
	VrfTableId     uint32
	EgressKind     uint32
	Packets        uint64
	Bytes          uint64
	LastSeenNs     uint64
	Generation     uint64
	DroppedPackets uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	UsidMapDropReasons   = "drop_reasons"
	UsidMapFunctionTable = "function_table"
	UsidMapLocatorTable  = "locator_table"
	UsidMapVrfTable      = "vrf_table"
	UsidProgUsidIngress  = "usid_ingress"
)

// LoadUsid returns the embedded CollectionSpec for Usid.
func LoadUsid() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_UsidBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Usid: %w", err)
	}

	return spec, err
}

// LoadUsidObjects loads Usid and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*UsidObjects
//	*UsidPrograms
//	*UsidMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadUsidObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadUsid()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// UsidSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsidSpecs struct {
	UsidProgramSpecs
	UsidMapSpecs
	UsidVariableSpecs
}

// UsidProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsidProgramSpecs struct {
	UsidIngress *ebpf.ProgramSpec `ebpf:"usid_ingress"`
}

// UsidMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsidMapSpecs struct {
	DropReasons   *ebpf.MapSpec `ebpf:"drop_reasons"`
	FunctionTable *ebpf.MapSpec `ebpf:"function_table"`
	LocatorTable  *ebpf.MapSpec `ebpf:"locator_table"`
	VrfTable      *ebpf.MapSpec `ebpf:"vrf_table"`
}

// UsidVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type UsidVariableSpecs struct {
}

// UsidObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadUsidObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsidObjects struct {
	UsidPrograms
	UsidMaps
	UsidVariables
}

func (o *UsidObjects) Close() error {
	return _UsidClose(
		&o.UsidPrograms,
		&o.UsidMaps,
	)
}

// UsidMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadUsidObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsidMaps struct {
	DropReasons   *ebpf.Map `ebpf:"drop_reasons"`
	FunctionTable *ebpf.Map `ebpf:"function_table"`
	LocatorTable  *ebpf.Map `ebpf:"locator_table"`
	VrfTable      *ebpf.Map `ebpf:"vrf_table"`
}

func (m *UsidMaps) Close() error {
	return _UsidClose(
		m.DropReasons,
		m.FunctionTable,
		m.LocatorTable,
		m.VrfTable,
	)
}

// UsidVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadUsidObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsidVariables struct {
}

// UsidPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadUsidObjects or ebpf.CollectionSpec.LoadAndAssign.
type UsidPrograms struct {
	UsidIngress *ebpf.Program `ebpf:"usid_ingress"`
}

func (p *UsidPrograms) Close() error {
	return _UsidClose(
		p.UsidIngress,
	)
}

func _UsidClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed usid_bpfeb.o
var _UsidBytes []byte
