apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpc20
  namespace: vpc
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vpc20",
      "type": "galactic-cni",
      "vpc": "20",
      "vpcattachment": "20",
      "namespace": "galactic-system",
      "ipam": {
        "type": "pool",
        "pool": "fd00:20:ff03::/48",
        "gateway": "fd00:20:ff03::1",
        "subnet_len": 80
      }
    }
