apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-cni
spec:
  template:
    spec:
      # Both uplinks
      initContainers:
        - name: install-cni
          env:
            - name: GALACTIC_CNI_EBPF_INTERFACES
              value: eth1,eth2
      containers:
        - name: credential-refresh
          env:
            - name: GALACTIC_CNI_EBPF_INTERFACES
              value: eth1,eth2
