apiVersion: network.datumapis.com/v1alpha1
kind: BGPRouter
metadata:
  name: dfw-worker-tenant
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: dfw-worker
  roles:
    - tenant
  localASN: 65000
  routerID: "10.0.1.1"
  srv6Locator: "2001:db8:ff01::/48"
  nodeID: 1
  addressFamilies:
    - afi: l2vpn
      safi: evpn
