apiVersion: providers.bgp.miloapis.com/v1alpha1
kind: BGPProvider
metadata:
  name: iad-worker-gobgp
  labels:
    bgp.datum.net/plane: overlay
    bgp.miloapis.com/daemon: gobgp
    bgp.miloapis.com/node: iad-worker
spec:
  type: GoBGP
  gobgp:
    endpoint: localhost:50051
