apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPSession
metadata:
  name: iad-overlay-to-infra-rr
spec:
  fromProviderSelector:
    matchLabels:
      bgp.datum.net/plane: overlay
      bgp.miloapis.com/daemon: gobgp
  fromInstanceRef: overlay
  toPeers:
    - address: "fc00:0:4::1"
      asNumber: 65000
      instanceRef: overlay
      routeReflectorClient: false
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
  timers:
    holdTime: 90
    keepalive: 30
