apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-cni
spec:
  template:
    spec:
      initContainers:
        - name: install-cni
          image: __GALACTIC_CNI_IMAGE__
          imagePullPolicy: Always
      containers:
        - name: credential-refresh
          image: __GALACTIC_CNI_IMAGE__
          imagePullPolicy: Always
