apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    app: private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private
  template:
    metadata:
      labels:
        app: private
      annotations:
        v1.multus-cni.io/default-network: private
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
