apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPInstance
metadata:
  name: overlay
spec:
  providerSelector:
    matchLabels:
      galactic.io/plane: overlay
  asNumber: 65000
  listenPort: 1790
  routerIDSource: Auto
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
