apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: overlay-to-rr
spec:
  instanceRef: overlay
  providerSelector:
    matchLabels:
      galactic.io/role: overlay
  address: "fc00:0:8::1"
  asNumber: 65000
  remotePort: 1179
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
