apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPAdvertisement
metadata:
  name: iad-overlay-sid
  namespace: galactic-system
spec:
  routerRef:
    name: iad-overlay
  addressFamily:
    afi: l2vpn
    safi: evpn
  prefixes:
    - "2001:db8:ff03:100:ffff:ffff:ffff:ffff/128"
