apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPInstance
metadata:
  name: overlay
spec:
  providerSelector:
    matchLabels:
      galactic.io/plane: overlay
  asNumber: 65000
  routerIDSource: Manual
  routerID: "10.255.255.1"
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
  listenPort: 1179
  routeReflector:
    clusterID: "10.255.255.1"
