apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: overlay-to-iad
spec:
  instanceRef: overlay
  providerSelector:
    matchLabels:
      galactic.io/plane: overlay
  address: "fc00:0:2::1"
  asNumber: 65000
  passive: true
  routeReflectorClient: true
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
---
apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: overlay-to-sjc
spec:
  instanceRef: overlay
  providerSelector:
    matchLabels:
      galactic.io/plane: overlay
  address: "fc00:0:3::1"
  asNumber: 65000
  passive: true
  routeReflectorClient: true
  addressFamilies:
    - afi: L2VPN
      safi: EVPN
