apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: iad-overlay-to-rr
  namespace: galactic-system
spec:
  routerRef:
    name: iad-overlay
  peerASN: 65000
  address: "fc00:0:8::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
