apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: testvpc-3
  namespace: vpc
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "testvpc-3",
      "type": "galactic-cni",
      "vpc": "12",
      "vpcattachment": "12",
      "namespace": "galactic-system",
      "srv6_sid": "2001:db8:ff01::3/128",
      "ipam": {
        "type": "pool",
        "pool": "fd00:12:ff01::/48",
        "gateway": "fd00:12:ff01::1",
        "subnet_len": 80
      }
    }
