FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace

COPY README.md pyproject.toml ./
COPY .flake8 ./.flake8
COPY alembic ./alembic
COPY features ./features
COPY galactic_router ./galactic_router

RUN python -m pip install --no-cache-dir --upgrade pip && \
    python -m pip install --no-cache-dir -e .[test,lint]

RUN flake8 -v .
RUN behave
