apiVersion: network.datumapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: iad-control-tenant-to-sjc
  namespace: galactic-system
spec:
  routerRef:
    name: iad-control-tenant
  peerASN: 65000
  address: "fc00:0:3::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
