apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPAdvertisement
metadata:
  name: sjc-worker-tenant-sid
  namespace: galactic-system
spec:
  routerRef:
    name: sjc-worker-tenant
  addressFamily:
    afi: l2vpn
    safi: evpn
  prefixes:
    - "2001:db8:ff02::1/128"
    - "2001:db8:ff02::2/128"
