frr defaults traditional
hostname tr3
log syslog informational

interface lo
 ipv6 address fc00:0:6::1/128
!
interface eth1
 description tr1-facing
 ipv6 address 2001:db8:0:13::3/64
!
interface eth2
 description tr2-facing
 ipv6 address 2001:db8:0:23::3/64
!
interface eth3
 description tr4-facing
 ipv6 address 2001:db8:0:34::3/64
!
interface eth4
 description iad-control-worker-facing
 ipv6 address 2001:db8:1:31::1/64
!
interface eth5
 description iad-worker-facing
 ipv6 address 2001:db8:1:30::1/64
!

ipv6 prefix-list MIN48 seq 5 prefix ::/0 le 48 permit
ipv6 prefix-list MIN48 seq 10 deny
route-map FILTER_PREFIX deny 10
 match ipv6 address prefix-list MIN48
route-map FILTER_PREFIX permit 20

router bgp 65100
 bgp router-id 10.255.255.102
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 neighbor 2001:db8:1:30::2 remote-as 65000
 neighbor 2001:db8:1:31::2 remote-as 65000
 neighbor eth1 interface remote-as 65100
 neighbor eth2 interface remote-as 65100
 neighbor eth3 interface remote-as 65100
 !
 address-family ipv6 unicast
  neighbor 2001:db8:1:30::2 activate
  neighbor 2001:db8:1:30::2 route-map FILTER_PREFIX in
  neighbor 2001:db8:1:31::2 activate
  neighbor 2001:db8:1:31::2 route-map FILTER_PREFIX in
  neighbor eth1 activate
  neighbor eth1 next-hop-self
  neighbor eth1 route-map FILTER_PREFIX in
  neighbor eth2 activate
  neighbor eth2 next-hop-self
  neighbor eth2 route-map FILTER_PREFIX in
  neighbor eth3 activate
  neighbor eth3 next-hop-self
  neighbor eth3 route-map FILTER_PREFIX in
  network fc00:0:6::1/128
 exit-address-family
!

ipv6 forwarding
