apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpc10
  namespace: vpc
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vpc10",
      "type": "galactic-cni",
      "vpc": "10",
      "vpcattachment": "10",
      "namespace": "galactic-system",
      "ipam": {
        "type": "pool",
        "pool": "fd00:10:ff01::/48",
        "gateway": "fd00:10:ff01::1",
        "subnet_len": 80
      }
    }
