apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpc10
  namespace: vpc
  labels:
    app: vpc10
    site: dfw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpc10
  template:
    metadata:
      labels:
        app: vpc10
        site: dfw
      annotations:
        k8s.v1.cni.cncf.io/networks: vpc10
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: multitool
          image: wbitt/network-multitool
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
