// Copyright 2026 Datum Cloud, Inc.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

package edgeprog

import (
	"encoding/binary"
	"net/netip"
	"testing"
)

// ICMPv6 message types/lengths used by the tests below (galactic#404).
// Kept local to this file rather than added to edgenat.c's own constants
// -- these mirror RFC 4443, not anything this program's C code needs a
// Go-side name for.
const (
	icmpv6DestUnreachable      = uint8(1)
	icmpv6PacketTooBig         = uint8(2)
	icmpv6TimeExceeded         = uint8(3)
	icmpv6RouterSolicitation   = uint8(133) // an arbitrary "not handled" type
	icmpv6EchoRequest          = uint8(128)
	icmpv6EchoReply            = uint8(129)
	icmp6EchoHdrLen            = 8 // type+code+check+identifier+sequence
	icmp6ErrHdrLen             = 8 // type+code+check+4 type-specific bytes
	icmp6EmbeddedPortsMinBytes = 8 // RFC 4443's guaranteed minimum embedded-transport-header length
)

// buildICMPv6EchoPacket returns a full Ethernet+IPv6+ICMPv6 Echo
// Request/Reply frame (identifier+sequence, no payload) with a correct
// checksum.
func buildICMPv6EchoPacket(src, dst netip.Addr, icmpType uint8, identifier, sequence uint16) []byte {
	pkt := make([]byte, ethHdrLen+ip6HdrLen+icmp6EchoHdrLen)
	binary.BigEndian.PutUint16(pkt[12:14], 0x86DD)

	ip6 := pkt[ethHdrLen:]
	ip6[0] = 0x60
	binary.BigEndian.PutUint16(ip6[4:6], icmp6EchoHdrLen)
	ip6[6] = 58 // ICMPv6
	ip6[7] = 64
	sb, db := src.As16(), dst.As16()
	copy(ip6[8:24], sb[:])
	copy(ip6[24:40], db[:])

	icmp := ip6[ip6HdrLen:]
	icmp[0] = icmpType
	icmp[1] = 0
	binary.BigEndian.PutUint16(icmp[4:6], identifier)
	binary.BigEndian.PutUint16(icmp[6:8], sequence)
	binary.BigEndian.PutUint16(icmp[2:4], 0)

	csum := ipv6L4Checksum(src, dst, 58, icmp)
	binary.BigEndian.PutUint16(icmp[2:4], csum)

	return pkt
}

// buildEncappedICMPv6EchoPacket wraps buildICMPv6EchoPacket's inner frame
// in an outer IPv6-in-IPv6 (nexthdr=41) header, mirroring
// buildEncappedTCPPacket -- the wire shape of a tenant backend's own Echo
// Request arriving SRv6-encapsulated and addressed to egress_sid.
func buildEncappedICMPv6EchoPacket(
	outerSrc, outerDst, innerSrc, innerDst netip.Addr, icmpType uint8, identifier, sequence uint16,
) []byte {
	inner := buildICMPv6EchoPacket(innerSrc, innerDst, icmpType, identifier, sequence)[ethHdrLen:]

	pkt := make([]byte, ethHdrLen+ip6HdrLen+len(inner))
	binary.BigEndian.PutUint16(pkt[12:14], 0x86DD)

	outer := pkt[ethHdrLen:]
	outer[0] = 0x60
	binary.BigEndian.PutUint16(outer[4:6], uint16(len(inner)))
	outer[6] = 41
	outer[7] = 64
	sb, db := outerSrc.As16(), outerDst.As16()
	copy(outer[8:24], sb[:])
	copy(outer[24:40], db[:])

	copy(pkt[ethHdrLen+ip6HdrLen:], inner)
	return pkt
}

// buildICMPv6ErrorPacket returns a full Ethernet+IPv6+ICMPv6-error frame,
// as if generated by an intermediate router (routerAddr) in response to a
// packet this program itself sent -- masqAddr:masqPort -> destAddr:destPort,
// embeddedProto -- truncated to embeddedLen bytes of that packet's own
// transport header. RFC 4443 guarantees only the first 8 bytes, so a
// caller passing icmp6EmbeddedPortsMinBytes exercises the minimal,
// worst-case shape parse_embedded_ports (not parse_l4) is specifically
// written to survive -- a full 20-byte TCP header is not guaranteed to be
// present, only its first 8 bytes are, and both port fields live there.
func buildICMPv6ErrorPacket(
	routerAddr, masqAddr, destAddr netip.Addr,
	icmpType, embeddedProto uint8, masqPort, destPort uint16, embeddedLen int,
) []byte {
	embedded := make([]byte, ip6HdrLen+embeddedLen)
	embedded[0] = 0x60
	binary.BigEndian.PutUint16(embedded[4:6], uint16(embeddedLen))
	embedded[6] = embeddedProto
	embedded[7] = 64
	ma, da := masqAddr.As16(), destAddr.As16()
	copy(embedded[8:24], ma[:])
	copy(embedded[24:40], da[:])
	if embeddedLen >= 4 {
		binary.BigEndian.PutUint16(embedded[40:42], masqPort)
		binary.BigEndian.PutUint16(embedded[42:44], destPort)
	}

	pkt := make([]byte, ethHdrLen+ip6HdrLen+icmp6ErrHdrLen+len(embedded))
	binary.BigEndian.PutUint16(pkt[12:14], 0x86DD)

	ip6 := pkt[ethHdrLen:]
	ip6[0] = 0x60
	binary.BigEndian.PutUint16(ip6[4:6], uint16(icmp6ErrHdrLen+len(embedded)))
	ip6[6] = 58 // ICMPv6
	ip6[7] = 64
	ra := routerAddr.As16()
	copy(ip6[8:24], ra[:])
	copy(ip6[24:40], ma[:]) // dst = masqAddr, the original packet's own source

	icmp := ip6[ip6HdrLen:]
	icmp[0] = icmpType
	icmp[1] = 0
	// icmp[4:8] (the type-specific 4 bytes) left zero -- never read.
	copy(icmp[icmp6ErrHdrLen:], embedded)
	binary.BigEndian.PutUint16(icmp[2:4], 0)

	csum := ipv6L4Checksum(routerAddr, masqAddr, 58, icmp)
	binary.BigEndian.PutUint16(icmp[2:4], csum)

	return pkt
}

// testEgressReturnICMPErrorTranslatesToTenant is the shared body for the
// three RFC 4443 error-type tests below: a pre-seeded egress_conn_table
// reverse row plus an ICMPv6 error whose embedded datagram matches it must
// translate back to the originating tenant, not drop -- the issue's own
// "path MTU discovery" case (Packet Too Big) is the one with actual teeth,
// but Destination Unreachable and Time Exceeded share the identical fix.
func testEgressReturnICMPErrorTranslatesToTenant(t *testing.T, icmpType uint8) {
	t.Helper()

	backendAddr := mustAddr(t, testEgressBackendAddr)
	destAddr := mustAddr(t, testEgressDest)
	masqAddr := mustAddr(t, testEgressMasqAddr)
	workerUsid := mustAddr(t, testWorkerUsid1)
	gwAddr := mustAddr(t, testGWAddr)
	routerAddr := mustAddr(t, "2001:db8:ff::1") // an intermediate router; never asserted on
	const masqPort = uint16(45001)

	env, cleanup := setupTestEnv(t, []netip.Addr{workerUsid})
	defer cleanup()

	objs := loadObjects(t)
	installEgressConfig(t, objs)
	if err := objs.GwConfigTable.Put(uint32(0), EdgenatGwConfig{GwAddr: gwAddr.As16()}); err != nil {
		t.Fatalf("populate gw_config_table: %v", err)
	}

	rev := EdgenatEgressConnKey{
		Proto: 6, // TCP -- the flow this error message reports on
		Saddr: destAddr.As16(), Sport: htons(testEgressDestPort),
		Daddr: masqAddr.As16(), Dport: htons(masqPort),
	}
	cv := EdgenatEgressConnValue{
		TenantArg:   testTenantArg1,
		BackendAddr: backendAddr.As16(),
		BackendPort: htons(testEgressBackendPort),
		BackendUsid: workerUsid.As16(),
		DestAddr:    destAddr.As16(),
		DestPort:    htons(testEgressDestPort),
		MasqAddr:    masqAddr.As16(),
		MasqPort:    htons(masqPort),
		Proto:       6,
	}
	if err := objs.EgressConnTable.Put(rev, cv); err != nil {
		t.Fatalf("populate egress_conn_table reverse row: %v", err)
	}

	// embeddedLen == icmp6EmbeddedPortsMinBytes deliberately -- the RFC
	// 4443 guaranteed minimum, well short of a full 20-byte TCP header.
	pkt := buildICMPv6ErrorPacket(routerAddr, masqAddr, destAddr, icmpType, 6,
		masqPort, testEgressDestPort, icmp6EmbeddedPortsMinBytes)

	ret, out := runXDP(t, objs.EdgeNat, pkt, env.ifindex)
	if ret != xdpTx {
		t.Fatalf("verdict = %d, want XDP_TX (%d)", ret, xdpTx)
	}

	wantLen := len(pkt) + 40 // push_outer_header grows the packet by exactly 40 bytes
	out = out[:wantLen]
	parseEth(t, out)

	outer := out[ethHdrLen:]
	if got := outer[6]; got != 41 {
		t.Errorf("outer nexthdr = %d, want 41 (IPv6-in-IPv6)", got)
	}
	if got := netip.AddrFrom16([16]byte(outer[8:24])); got != gwAddr {
		t.Errorf("outer saddr = %s, want this gateway's own address %s", got, gwAddr)
	}
	if got := netip.AddrFrom16([16]byte(outer[24:40])); got != workerUsid {
		t.Errorf("outer daddr = %s, want the originating worker node's uSID %s", got, workerUsid)
	}

	inner := outer[ip6HdrLen:]
	if got := netip.AddrFrom16([16]byte(inner[24:40])); got != backendAddr {
		t.Errorf("inner (ICMPv6 packet's own) daddr = %s, want backend address %s (un-masqueraded)", got, backendAddr)
	}

	icmp := inner[ip6HdrLen:]
	if got := icmp[0]; got != icmpType {
		t.Errorf("icmp type = %d, want unchanged %d", got, icmpType)
	}
	embedded := icmp[icmp6ErrHdrLen:]
	if got := netip.AddrFrom16([16]byte(embedded[8:24])); got != backendAddr {
		t.Errorf("embedded saddr = %s, want backend address %s (un-masqueraded)", got, backendAddr)
	}
	if got := netip.AddrFrom16([16]byte(embedded[24:40])); got != destAddr {
		t.Errorf("embedded daddr = %s, want unchanged internet destination %s", got, destAddr)
	}
	if got := binary.BigEndian.Uint16(embedded[40:42]); got != testEgressBackendPort {
		t.Errorf("embedded source port = %d, want backend port %d (un-masqueraded)", got, testEgressBackendPort)
	}
	if got := binary.BigEndian.Uint16(embedded[42:44]); got != testEgressDestPort {
		t.Errorf("embedded dest port = %d, want unchanged %d", got, testEgressDestPort)
	}

	icmpZeroed := make([]byte, len(icmp))
	copy(icmpZeroed, icmp)
	binary.BigEndian.PutUint16(icmpZeroed[2:4], 0)
	wantCsum := ipv6L4Checksum(routerAddr, backendAddr, 58, icmpZeroed)
	if gotCsum := binary.BigEndian.Uint16(icmp[2:4]); gotCsum != wantCsum {
		t.Errorf("ICMPv6 checksum = %#04x, want %#04x (independently recomputed)", gotCsum, wantCsum)
	}
}

func TestEdgeNat_EgressReturnICMPDestUnreachableTranslatesToTenant(t *testing.T) {
	testEgressReturnICMPErrorTranslatesToTenant(t, icmpv6DestUnreachable)
}

// TestEdgeNat_EgressReturnICMPPacketTooBigTranslatesToTenant is the issue's
// own headline case: Packet Too Big is how path MTU discovery reaches a
// tenant. Dropping it (the pre-#404 behavior) is what stalled large
// transfers on smaller-MTU paths instead of letting them adapt.
func TestEdgeNat_EgressReturnICMPPacketTooBigTranslatesToTenant(t *testing.T) {
	testEgressReturnICMPErrorTranslatesToTenant(t, icmpv6PacketTooBig)
}

func TestEdgeNat_EgressReturnICMPTimeExceededTranslatesToTenant(t *testing.T) {
	testEgressReturnICMPErrorTranslatesToTenant(t, icmpv6TimeExceeded)
}

// TestEdgeNat_EgressReturnICMPUnknownConnDrops covers an ICMPv6 error
// message whose embedded tuple matches no egress_conn_table row -- the
// address is claimed, so this must drop, with a reason distinct from the
// TCP/UDP path's own DROP_REASON_NO_EGRESS_RETURN_CONN (the review comment
// on #381 asked for exactly this distinction).
func TestEdgeNat_EgressReturnICMPUnknownConnDrops(t *testing.T) {
	requireRoot(t)
	objs := loadObjects(t)
	installEgressConfig(t, objs)
	if err := objs.GwConfigTable.Put(uint32(0), EdgenatGwConfig{GwAddr: mustAddr(t, testGWAddr).As16()}); err != nil {
		t.Fatalf("populate gw_config_table: %v", err)
	}

	pkt := buildICMPv6ErrorPacket(
		mustAddr(t, "2001:db8:ff::1"), mustAddr(t, testEgressMasqAddr), mustAddr(t, testEgressDest),
		icmpv6DestUnreachable, 6, 45999, testEgressDestPort, icmp6EmbeddedPortsMinBytes,
	)
	ret, _ := runXDP(t, objs.EdgeNat, pkt, 1)
	if ret != xdpDrop {
		t.Fatalf("verdict = %d, want XDP_DROP (%d)", ret, xdpDrop)
	}

	got := sumPerCPU(t, objs.DropReasons, DropReasonNoEgressICMPConn)
	if got != 1 {
		t.Errorf("drop_reasons[no_egress_icmp_conn] = %d, want 1", got)
	}
}

// TestEdgeNat_EgressReturnUnhandledICMPPassesThrough covers an ICMPv6 type
// that is neither Echo Reply nor a recognized error type (a Router
// Solicitation, here) arriving addressed to masq_addr -- this must
// XDP_PASS, not XDP_DROP, the actual "pass or handle the rest" behavior
// change #404 asks for, handing it to the normal kernel stack instead of
// claiming and dropping it.
func TestEdgeNat_EgressReturnUnhandledICMPPassesThrough(t *testing.T) {
	requireRoot(t)
	objs := loadObjects(t)
	installEgressConfig(t, objs)

	pkt := buildICMPv6EchoPacket(mustAddr(t, testEgressDest), mustAddr(t, testEgressMasqAddr),
		icmpv6RouterSolicitation, 0, 0)
	ret, out := runXDP(t, objs.EdgeNat, pkt, 1)
	if ret != xdpPass {
		t.Fatalf("verdict = %d, want XDP_PASS (%d)", ret, xdpPass)
	}
	if string(out[:len(pkt)]) != string(pkt) {
		t.Error("XDP_PASS packet was modified, want byte-for-byte untouched")
	}
}

// TestEdgeNat_EgressForwardICMPNonEchoRequestDrops covers a tenant backend
// sending some other ICMPv6 type (an Echo Reply, here) out via egress_sid
// -- there is no defined masquerade behavior for it, so this must drop,
// not pass through (egress_sid is claimed).
func TestEdgeNat_EgressForwardICMPNonEchoRequestDrops(t *testing.T) {
	requireRoot(t)
	objs := loadObjects(t)
	installEgressConfig(t, objs)

	pkt := buildEncappedICMPv6EchoPacket(
		mustAddr(t, testWorkerUsid1), egressSIDAddr(t, testTenantArg1),
		mustAddr(t, testEgressBackendAddr), mustAddr(t, testEgressDest),
		icmpv6EchoReply, 0x1234, 1,
	)
	ret, _ := runXDP(t, objs.EdgeNat, pkt, 1)
	if ret != xdpDrop {
		t.Fatalf("verdict = %d, want XDP_DROP (%d)", ret, xdpDrop)
	}

	got := sumPerCPU(t, objs.DropReasons, DropReasonMalformedEgressICMP)
	if got != 1 {
		t.Errorf("drop_reasons[malformed_egress_icmp] = %d, want 1", got)
	}
}

// TestEdgeNat_EgressPingRoundTrip covers the full ping round trip #404
// asks for: a tenant backend's Echo Request must masquerade both the
// source address and the identifier on the way out, and the internet
// peer's Echo Reply (which always echoes the identifier it was sent
// unchanged) must restore both the destination address and the tenant's
// own original identifier on the way back -- the identifier restoration
// is the part easy to get wrong; getting only the address right would
// still leave the tenant's own ping process unable to recognize the reply.
func TestEdgeNat_EgressPingRoundTrip(t *testing.T) {
	backendAddr := mustAddr(t, testEgressBackendAddr)
	destAddr := mustAddr(t, testEgressDest)
	masqAddr := mustAddr(t, testEgressMasqAddr)
	workerUsid := mustAddr(t, testWorkerUsid1)
	gwAddr := mustAddr(t, testGWAddr)
	const identifier = uint16(0xabcd)
	const sequence = uint16(1)

	env, cleanup := setupTestEnv(t, []netip.Addr{destAddr, workerUsid})
	defer cleanup()

	objs := loadObjects(t)
	installEgressConfig(t, objs)
	if err := objs.GwConfigTable.Put(uint32(0), EdgenatGwConfig{GwAddr: gwAddr.As16()}); err != nil {
		t.Fatalf("populate gw_config_table: %v", err)
	}

	// Forward: the tenant backend's Echo Request leaves via egress_sid.
	fwdPkt := buildEncappedICMPv6EchoPacket(
		workerUsid, egressSIDAddr(t, testTenantArg1),
		backendAddr, destAddr,
		icmpv6EchoRequest, identifier, sequence,
	)
	fwdRet, fwdOut := runXDP(t, objs.EdgeNat, fwdPkt, env.ifindex)
	if fwdRet != xdpTx {
		t.Fatalf("forward verdict = %d, want XDP_TX (%d)", fwdRet, xdpTx)
	}

	fwdWantLen := ethHdrLen + ip6HdrLen + icmp6EchoHdrLen
	fwdOut = fwdOut[:fwdWantLen]
	fwdIP6 := fwdOut[ethHdrLen:]
	if got := netip.AddrFrom16([16]byte(fwdIP6[8:24])); got != masqAddr {
		t.Fatalf("forward saddr (SNAT) = %s, want masq_addr %s", got, masqAddr)
	}
	if got := netip.AddrFrom16([16]byte(fwdIP6[24:40])); got != destAddr {
		t.Fatalf("forward daddr = %s, want unchanged internet destination %s", got, destAddr)
	}
	fwdICMP := fwdIP6[ip6HdrLen:]
	gotMasqIdentifier := binary.BigEndian.Uint16(fwdICMP[4:6])
	if gotMasqIdentifier == identifier {
		t.Fatalf("masqueraded identifier = original identifier %#04x, want a re-mapped value", identifier)
	}

	fwdICMPZeroed := make([]byte, len(fwdICMP))
	copy(fwdICMPZeroed, fwdICMP)
	binary.BigEndian.PutUint16(fwdICMPZeroed[2:4], 0)
	wantFwdCsum := ipv6L4Checksum(masqAddr, destAddr, 58, fwdICMPZeroed)
	if gotCsum := binary.BigEndian.Uint16(fwdICMP[2:4]); gotCsum != wantFwdCsum {
		t.Errorf("forward ICMPv6 checksum = %#04x, want %#04x (independently recomputed)", gotCsum, wantFwdCsum)
	}

	// Return: the internet peer echoes the request back unchanged, still
	// addressed using the masqueraded identifier it actually received --
	// the real-world behavior an Echo Reply always has.
	retPkt := buildICMPv6EchoPacket(destAddr, masqAddr, icmpv6EchoReply, gotMasqIdentifier, sequence)
	retRet, retOut := runXDP(t, objs.EdgeNat, retPkt, env.ifindex)
	if retRet != xdpTx {
		t.Fatalf("return verdict = %d, want XDP_TX (%d)", retRet, xdpTx)
	}

	retWantLen := len(retPkt) + 40
	retOut = retOut[:retWantLen]
	parseEth(t, retOut)

	outer := retOut[ethHdrLen:]
	if got := outer[6]; got != 41 {
		t.Errorf("outer nexthdr = %d, want 41 (IPv6-in-IPv6)", got)
	}
	if got := netip.AddrFrom16([16]byte(outer[8:24])); got != gwAddr {
		t.Errorf("outer saddr = %s, want this gateway's own address %s", got, gwAddr)
	}
	if got := netip.AddrFrom16([16]byte(outer[24:40])); got != workerUsid {
		t.Errorf("outer daddr = %s, want the originating worker node's uSID %s", got, workerUsid)
	}

	inner := outer[ip6HdrLen:]
	if got := netip.AddrFrom16([16]byte(inner[8:24])); got != destAddr {
		t.Errorf("inner saddr = %s, want unchanged internet peer address %s", got, destAddr)
	}
	if got := netip.AddrFrom16([16]byte(inner[24:40])); got != backendAddr {
		t.Errorf("inner daddr (DNAT) = %s, want backend address %s", got, backendAddr)
	}

	innerICMP := inner[ip6HdrLen:]
	if got := innerICMP[0]; got != icmpv6EchoReply {
		t.Errorf("icmp type = %d, want unchanged Echo Reply (%d)", got, icmpv6EchoReply)
	}
	if got := binary.BigEndian.Uint16(innerICMP[4:6]); got != identifier {
		t.Errorf("restored identifier = %#04x, want tenant's original %#04x", got, identifier)
	}
	if got := binary.BigEndian.Uint16(innerICMP[6:8]); got != sequence {
		t.Errorf("sequence = %d, want unchanged %d", got, sequence)
	}

	innerICMPZeroed := make([]byte, len(innerICMP))
	copy(innerICMPZeroed, innerICMP)
	binary.BigEndian.PutUint16(innerICMPZeroed[2:4], 0)
	wantRetCsum := ipv6L4Checksum(destAddr, backendAddr, 58, innerICMPZeroed)
	if gotCsum := binary.BigEndian.Uint16(innerICMP[2:4]); gotCsum != wantRetCsum {
		t.Errorf("return ICMPv6 checksum = %#04x, want %#04x (independently recomputed)", gotCsum, wantRetCsum)
	}
}
