---
apiVersion: v1
kind: Namespace
metadata:
  name: sjc-overlay

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sjc-overlay-config
  namespace: sjc-overlay
data:
  gobgp.conf: |
    [global.config]
      as = 65000
      router-id = "10.255.255.3"
      port = -1
      local-address-list = ["fc00:0:3::1"]

    [[neighbors]]
      [neighbors.config]
        neighbor-address = "fc00:0:4::1"
        peer-as = 65000
        description = "infra-control-plane"
      [neighbors.transport.config]
        local-address = "fc00:0:3::1"
      [[neighbors.afi-safis]]
        [neighbors.afi-safis.config]
          afi-safi-name = "l3vpn-ipv6-unicast"

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sjc-overlay
  namespace: sjc-overlay
  labels:
    app.kubernetes.io/name: sjc-overlay
    app.kubernetes.io/instance: sjc-overlay
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sjc-overlay
      app.kubernetes.io/instance: sjc-overlay
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sjc-overlay
        app.kubernetes.io/instance: sjc-overlay
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      hostNetwork: true
      containers:
        - name: gobgp
          image: osrg/gobgp:latest
          imagePullPolicy: Never
          command:
            - gobgpd
            - -f
            - /etc/gobgp/gobgp.conf
            - --api-hosts
            - :50051
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: gobgp-config
              mountPath: /etc/gobgp
              readOnly: true
      volumes:
        - name: gobgp-config
          configMap:
            name: sjc-overlay-config
