apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPRouter
metadata:
  name: sjc-overlay
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: sjc-worker
  roles:
    - tenant
  localASN: 65000
  routerID: "10.0.3.1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
