frr version 9.1
frr defaults traditional
hostname rr2
log syslog informational

interface lo
 ipv6 address fc00:0:8::1/128
!
interface eth1
 description tr4-facing
 ipv6 address 2001:db8:0:4::2/64
!

router bgp 65000
 bgp router-id 10.255.255.4
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as 65100
 neighbor eth1 local-as 65104 no-prepend replace-as
 neighbor fc00:0:2::1 remote-as 65000
 neighbor fc00:0:2::1 update-source lo
 neighbor fc00:0:3::1 remote-as 65000
 neighbor fc00:0:3::1 update-source lo
 !
 address-family ipv6 unicast
  neighbor eth1 activate
  network fc00:0:8::1/128
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor fc00:0:2::1 activate
  neighbor fc00:0:2::1 route-reflector-client
  neighbor fc00:0:3::1 activate
  neighbor fc00:0:3::1 route-reflector-client
 exit-address-family
!

ipv6 forwarding
