apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bgp.galactic.datumapis.com_bgpconfigurations.yaml
  - bgp.galactic.datumapis.com_bgpendpoints.yaml
  - bgp.galactic.datumapis.com_bgpsessions.yaml
  - bgp.galactic.datumapis.com_bgppeeringpolicies.yaml
  - bgp.galactic.datumapis.com_bgpadvertisements.yaml
  - bgp.galactic.datumapis.com_bgproutepolicies.yaml
