frr version 9.1
frr defaults traditional
hostname tr4
log syslog informational

interface lo
 ipv6 address fc00:0:7::1/128
!
interface eth1
 description tr1-facing
 ipv6 address 2001:db8:0:14::4/64
!
interface eth2
 description tr2-facing
 ipv6 address 2001:db8:0:24::4/64
!
interface eth3
 description tr3-facing
 ipv6 address 2001:db8:0:34::4/64
!

router bgp 65100
 bgp router-id 10.255.255.103
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 neighbor eth1 interface remote-as 65100
 neighbor eth2 interface remote-as 65100
 neighbor eth3 interface remote-as 65100
 !
 address-family ipv6 unicast
  neighbor eth1 activate
  neighbor eth1 next-hop-self
  neighbor eth2 activate
  neighbor eth2 next-hop-self
  neighbor eth3 activate
  neighbor eth3 next-hop-self
  network fc00:0:7::1/128
 exit-address-family
!

ipv6 forwarding
