apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: galactic
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "galactic",
      "type": "galactic-cni",
      "vpc": "1",
      "vpcattachment": "1",
      "srv6_locator": "2001:db8:ff03::/48",
      "galacticRouter": {
        "address": "127.0.0.1:50051"
      }
    }
