apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPAdvertisement
metadata:
  name: iad-worker-vpc20-sid
  namespace: galactic-system
spec:
  routerRef:
    name: iad-worker-tenant
  addressFamily:
    afi: l2vpn
    safi: evpn
  prefixes:
    - "2001:db8:ff03::2/128"
