apiVersion: network.datumapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: iad-worker-tenant-to-rr
  namespace: galactic-system
spec:
  routerRef:
    name: iad-worker-tenant
  peerASN: 65000
  address: "fc00:0:8::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
