apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPRouter
metadata:
  name: iad-worker-tenant
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: iad-worker
  roles:
    - tenant
  localASN: 65000
  routerID: "10.0.2.1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
