frr version 9.1
frr defaults traditional
hostname tr3
log syslog informational

interface lo
 ipv6 address fc00:0:6::1/128
!
interface eth1
 description tr1-facing
 ipv6 address 2001:db8:0:13::3/64
!
interface eth2
 description tr2-facing
 ipv6 address 2001:db8:0:23::3/64
!
interface eth3
 description tr4-facing
 ipv6 address 2001:db8:0:34::3/64
!
interface eth4
 description rr1-facing
 ipv6 address 2001:db8:0:3::1/64
!

router bgp 65100
 bgp router-id 10.255.255.102
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 neighbor eth1 interface remote-as 65100
 neighbor eth2 interface remote-as 65100
 neighbor eth3 interface remote-as 65100
 neighbor eth4 interface remote-as 65103
 !
 address-family ipv6 unicast
  neighbor eth1 activate
  neighbor eth1 next-hop-self
  neighbor eth2 activate
  neighbor eth2 next-hop-self
  neighbor eth3 activate
  neighbor eth3 next-hop-self
  neighbor eth4 activate
  network fc00:0:6::1/128
 exit-address-family
!

ipv6 forwarding
