apiVersion: network.datumapis.com/v1alpha1
kind: BGPRouter
metadata:
  name: galactic-router-sjc-worker2
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: sjc-worker2
  localASN: 65000
  routerID: "10.0.3.2"
  srv6Locator: "2001:db8:ff02::/48"
  nodeID: 2
  addressFamilies:
    - afi: l2vpn
      safi: evpn
