apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: iad-rr-overlay-to-sjc
  namespace: galactic-system
spec:
  routerRef:
    name: iad-rr-overlay
  peerASN: 65000
  address: "fc00:0:3::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
