apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPRouter
metadata:
  name: iad-rr-overlay
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: iad-worker-rr
  roles:
    - tenant
  localASN: 65000
  routerID: "10.255.255.4"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
