apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fabric-router
spec:
  template:
    spec:
      initContainers:
        - name: frr-init
          image: fabric-router:latest
          imagePullPolicy: Never
      containers:
        - name: frr
          image: fabric-router:latest
          imagePullPolicy: Never
