//go:build !ignore_autogenerated

// Copyright 2026 Datum Cloud, Inc.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASSegment) DeepCopyInto(out *ASSegment) {
	*out = *in
	if in.ASNs != nil {
		in, out := &in.ASNs, &out.ASNs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASSegment.
func (in *ASSegment) DeepCopy() *ASSegment {
	if in == nil {
		return nil
	}
	out := new(ASSegment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coverage) DeepCopyInto(out *Coverage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coverage.
func (in *Coverage) DeepCopy() *Coverage {
	if in == nil {
		return nil
	}
	out := new(Coverage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuery) DeepCopyInto(out *FabricQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuery.
func (in *FabricQuery) DeepCopy() *FabricQuery {
	if in == nil {
		return nil
	}
	out := new(FabricQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQueryList) DeepCopyInto(out *FabricQueryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FabricQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQueryList.
func (in *FabricQueryList) DeepCopy() *FabricQueryList {
	if in == nil {
		return nil
	}
	out := new(FabricQueryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FabricQueryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQuerySpec) DeepCopyInto(out *FabricQuerySpec) {
	*out = *in
	out.Source = in.Source
	out.Query = in.Query
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Budgets = in.Budgets
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQuerySpec.
func (in *FabricQuerySpec) DeepCopy() *FabricQuerySpec {
	if in == nil {
		return nil
	}
	out := new(FabricQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricQueryStatus) DeepCopyInto(out *FabricQueryStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeTarget, len(*in))
		copy(*out, *in)
	}
	if in.Observations != nil {
		in, out := &in.Observations, &out.Observations
		*out = make([]NodeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Coverage = in.Coverage
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricQueryStatus.
func (in *FabricQueryStatus) DeepCopy() *FabricQueryStatus {
	if in == nil {
		return nil
	}
	out := new(FabricQueryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hop) DeepCopyInto(out *Hop) {
	*out = *in
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = make([]ProbeReply, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hop.
func (in *Hop) DeepCopy() *Hop {
	if in == nil {
		return nil
	}
	out := new(Hop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexState) DeepCopyInto(out *IndexState) {
	*out = *in
	if in.SyncedAt != nil {
		in, out := &in.SyncedAt, &out.SyncedAt
		*out = (*in).DeepCopy()
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexState.
func (in *IndexState) DeepCopy() *IndexState {
	if in == nil {
		return nil
	}
	out := new(IndexState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Installation) DeepCopyInto(out *Installation) {
	*out = *in
	if in.SampleTime != nil {
		in, out := &in.SampleTime, &out.SampleTime
		*out = (*in).DeepCopy()
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]ZebraRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Installation.
func (in *Installation) DeepCopy() *Installation {
	if in == nil {
		return nil
	}
	out := new(Installation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextHop) DeepCopyInto(out *NextHop) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextHop.
func (in *NextHop) DeepCopy() *NextHop {
	if in == nil {
		return nil
	}
	out := new(NextHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeObservation) DeepCopyInto(out *NodeObservation) {
	*out = *in
	if in.SampleTime != nil {
		in, out := &in.SampleTime, &out.SampleTime
		*out = (*in).DeepCopy()
	}
	if in.Matched != nil {
		in, out := &in.Matched, &out.Matched
		*out = new(int32)
		**out = **in
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = new(RouteResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(SummaryResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Ping != nil {
		in, out := &in.Ping, &out.Ping
		*out = new(PingResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Traceroute != nil {
		in, out := &in.Traceroute, &out.Traceroute
		*out = new(TracerouteResult)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeObservation.
func (in *NodeObservation) DeepCopy() *NodeObservation {
	if in == nil {
		return nil
	}
	out := new(NodeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTarget) DeepCopyInto(out *NodeTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTarget.
func (in *NodeTarget) DeepCopy() *NodeTarget {
	if in == nil {
		return nil
	}
	out := new(NodeTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Path) DeepCopyInto(out *Path) {
	*out = *in
	if in.ASPathSegments != nil {
		in, out := &in.ASPathSegments, &out.ASPathSegments
		*out = make([]ASSegment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LocalPref != nil {
		in, out := &in.LocalPref, &out.LocalPref
		*out = new(int64)
		**out = **in
	}
	if in.MED != nil {
		in, out := &in.MED, &out.MED
		*out = new(int64)
		**out = **in
	}
	if in.Communities != nil {
		in, out := &in.Communities, &out.Communities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LargeCommunities != nil {
		in, out := &in.LargeCommunities, &out.LargeCommunities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NextHops != nil {
		in, out := &in.NextHops, &out.NextHops
		*out = make([]NextHop, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdate != nil {
		in, out := &in.LastUpdate, &out.LastUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Path.
func (in *Path) DeepCopy() *Path {
	if in == nil {
		return nil
	}
	out := new(Path)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peer) DeepCopyInto(out *Peer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peer.
func (in *Peer) DeepCopy() *Peer {
	if in == nil {
		return nil
	}
	out := new(Peer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PingResult) DeepCopyInto(out *PingResult) {
	*out = *in
	if in.Replies != nil {
		in, out := &in.Replies, &out.Replies
		*out = make([]ProbeReply, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PingResult.
func (in *PingResult) DeepCopy() *PingResult {
	if in == nil {
		return nil
	}
	out := new(PingResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixObservation) DeepCopyInto(out *PrefixObservation) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]Path, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Installation != nil {
		in, out := &in.Installation, &out.Installation
		*out = new(Installation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixObservation.
func (in *PrefixObservation) DeepCopy() *PrefixObservation {
	if in == nil {
		return nil
	}
	out := new(PrefixObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeReply) DeepCopyInto(out *ProbeReply) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeReply.
func (in *ProbeReply) DeepCopy() *ProbeReply {
	if in == nil {
		return nil
	}
	out := new(ProbeReply)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PublicQueryReference) DeepCopyInto(out *PublicQueryReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PublicQueryReference.
func (in *PublicQueryReference) DeepCopy() *PublicQueryReference {
	if in == nil {
		return nil
	}
	out := new(PublicQueryReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuerySpec) DeepCopyInto(out *QuerySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuerySpec.
func (in *QuerySpec) DeepCopy() *QuerySpec {
	if in == nil {
		return nil
	}
	out := new(QuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultBudgets) DeepCopyInto(out *ResultBudgets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultBudgets.
func (in *ResultBudgets) DeepCopy() *ResultBudgets {
	if in == nil {
		return nil
	}
	out := new(ResultBudgets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteResult) DeepCopyInto(out *RouteResult) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]PrefixObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(IndexState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteResult.
func (in *RouteResult) DeepCopy() *RouteResult {
	if in == nil {
		return nil
	}
	out := new(RouteResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SummaryResult) DeepCopyInto(out *SummaryResult) {
	*out = *in
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]Peer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SummaryResult.
func (in *SummaryResult) DeepCopy() *SummaryResult {
	if in == nil {
		return nil
	}
	out := new(SummaryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracerouteResult) DeepCopyInto(out *TracerouteResult) {
	*out = *in
	if in.Hops != nil {
		in, out := &in.Hops, &out.Hops
		*out = make([]Hop, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracerouteResult.
func (in *TracerouteResult) DeepCopy() *TracerouteResult {
	if in == nil {
		return nil
	}
	out := new(TracerouteResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZebraNextHop) DeepCopyInto(out *ZebraNextHop) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZebraNextHop.
func (in *ZebraNextHop) DeepCopy() *ZebraNextHop {
	if in == nil {
		return nil
	}
	out := new(ZebraNextHop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZebraRoute) DeepCopyInto(out *ZebraRoute) {
	*out = *in
	if in.NextHops != nil {
		in, out := &in.NextHops, &out.NextHops
		*out = make([]ZebraNextHop, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZebraRoute.
func (in *ZebraRoute) DeepCopy() *ZebraRoute {
	if in == nil {
		return nil
	}
	out := new(ZebraRoute)
	in.DeepCopyInto(out)
	return out
}
