apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cosmos-config/deploy/
images:
  - name: ghcr.io/milo-os/cosmos
    newName: cosmos
    newTag: latest
patches:
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
      name: cosmos
