apiVersion: bgp.miloapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: rr-infra
  namespace: default
spec:
  routerRef:
    name: tenant-node1
  peerASN: 65000
  address: fd00::1
  addressFamilies:
    - afi: l2vpn
      safi: evpn
  holdTime: 90s
  keepaliveTime: 30s
