apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: overlay
spec:
  template:
    spec:
      containers:
        - name: galactic-router
          env:
            - name: BGP_LOCAL_ADDRESS
              value: "fc00:0:3::1"
