[global.config]
  as = 65000
  router-id = "10.255.255.2"
  port = -1
  local-address-list = ["fc00:0:2::1"]

[[neighbors]]
  [neighbors.config]
    neighbor-address = "fc00:0:4::1"
    peer-as = 65000
    description = "rr1"
  [neighbors.transport.config]
    local-address = "fc00:0:2::1"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "fc00:0:8::1"
    peer-as = 65000
    description = "rr2"
  [neighbors.transport.config]
    local-address = "fc00:0:2::1"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l3vpn-ipv4-unicast"
