namespace: galactic-system
resources:
  - ../base

# One frr.conf.<nodename> key per node (dfw: compute, two edge workers)
configMapGenerator:
  - name: fabric-config
    files:
      - frr.conf.dfw-worker
      - frr.conf.dfw-worker2
      - frr.conf.dfw-worker3
