apiVersion: v1
kind: ConfigMap
metadata:
  name: underlay-config
  namespace: underlay
data:
  daemons: |
    zebra=yes
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=no
    fabricd=no
    vrrpd=no
    pathd=no

    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="  -A 127.0.0.1"
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname infra-underlay
    log syslog informational

    interface lo
     ipv6 address fc00:0:4::1/128
    !
    interface eth1
     description tr3-facing
    !

    ipv6 route 2001:db8:ff03::/48 Null0
    !
    router bgp 65000
     bgp router-id 10.255.255.1
     no bgp default ipv4-unicast
     no bgp ebgp-requires-policy
     bgp log-neighbor-changes
     neighbor eth1 interface remote-as 65100
     neighbor fc00:0:2::1 remote-as 65000
     neighbor fc00:0:2::1 update-source lo
     neighbor fc00:0:2::1 passive
     neighbor fc00:0:3::1 remote-as 65000
     neighbor fc00:0:3::1 update-source lo
     neighbor fc00:0:3::1 passive
     !
     address-family ipv6 unicast
      neighbor eth1 activate
      neighbor eth1 allowas-in 1
      network 2001:db8:ff03::/48
      network fc00:0:4::1/128
     exit-address-family
     !
     address-family ipv4 vpn
      neighbor fc00:0:2::1 activate
      neighbor fc00:0:2::1 route-reflector-client
      neighbor fc00:0:3::1 activate
      neighbor fc00:0:3::1 route-reflector-client
     exit-address-family
     !
     address-family ipv6 vpn
      neighbor fc00:0:2::1 activate
      neighbor fc00:0:2::1 route-reflector-client
      neighbor fc00:0:3::1 activate
      neighbor fc00:0:3::1 route-reflector-client
     exit-address-family
    !

    ipv6 forwarding
  vtysh.conf: |
    service integrated-vtysh-config
