apiVersion: v1
kind: ServiceAccount
metadata:
  name: galactic-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galactic-agent
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpconfigurations"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpconfigurations/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpendpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpendpoints/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpsessions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgpsessions/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgppeeringpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["bgp.galactic.datumapis.com"]
    resources: ["bgppeeringpolicies/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: galactic-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: galactic-agent
subjects:
  - kind: ServiceAccount
    name: galactic-agent
