apiVersion: network.datumapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: galactic-gateway-iad-gateway1
  namespace: galactic-system
spec:
  routerRef:
    name: galactic-control
  peerASN: 65000
  address: "fc00:0:9::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
