# Reflector-side session toward sjc-worker (sjc compute)
apiVersion: network.datumapis.com/v1alpha1
kind: BGPPeer
metadata:
  name: galactic-router-sjc-worker
  namespace: galactic-system
spec:
  routerRef:
    name: galactic-control
  peerASN: 65000
  address: "fc00:0:3::1"
  addressFamilies:
    - afi: l2vpn
      safi: evpn
