namespace: galactic-system
resources:
  - overlays/rr
  - bgprouter.yaml
  - bgppeer-dfw.yaml
  - bgppeer-iad.yaml
  - bgppeer-sjc.yaml
  - bgppeer-gateway1.yaml
  - bgppeer-gateway2.yaml
patches:
  - path: router-lab-patch.yaml
    target:
      kind: DaemonSet
      name: galactic-router
