apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-router
spec:
  template:
    spec:
      containers:
        - name: galactic-router
          env:
            - name: GALACTIC_ROUTER_BGP_LOCAL_ADDRESS
              value: "fc00:0:4::1"
