apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: testvpc
  namespace: vpc
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "testvpc",
      "type": "galactic-cni",
      "vpc": "10",
      "vpcattachment": "10",
      "namespace": "galactic-system",
      "srv6_sid": "2001:db8:ff00:1010::3/128",
      "ipam": {
        "type": "pool",
        "pool": "fd00:10:ff03::/48",
        "gateway": "fd00:10:ff03::1",
        "subnet_len": 80
      }
    }
