apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: overlay
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: galactic.io/role
                    operator: In
                    values:
                      - pop
      containers:
        - name: galactic-router
          env:
            - name: GALACTIC_ROUTER_BGP_LOCAL_ADDRESS
              value: "fc00:0:4::1"
