apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-nat
spec:
  template:
    spec:
      containers:
        - name: galactic-nat
          env:
            # single-homed node: eth1 uplink
            - name: GALACTIC_NAT_UPLINK_INTERFACES
              value: eth1
            # shard SID: uFMT uSID over iad's locator (2001:db8:ff03::/48), nodeID=9
            - name: GALACTIC_NAT_SHARD_SID
              value: "2001:db8:ff03:9:e001::"
            # NAT66 masquerade source address, docs-range 2001:db8:9966::/32 block
            - name: GALACTIC_NAT_SHARD_PUB_ADDR6
              value: "2001:db8:9966:2::1"
            # NAT64 masquerade source address (RFC 5737 TEST-NET-1)
            - name: GALACTIC_NAT_SHARD_PUB_ADDR4
              value: "192.0.2.2"
            - name: GALACTIC_NAT_NAT64_PREFIX
              value: "2001:db8:64::/96"
