namespace: ns71
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: netshoot
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: netshoot
      spec:
        template:
          metadata:
            annotations:
              v1.multus-cni.io/default-network: ns71/private
          spec:
            nodeSelector:
              galactic.datumapis.com/node: compute
