---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: private
  namespace: ns50
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "private",
      "type": "galactic-cni",
      "vpc": "50",
      "vpcattachment": "50",
      "namespace": "galactic-system",
      "ipam": {
        "type": "galactic-ipam",
        "ipv4_subnet": "172.20.20.0/24",
        "address_families": ["ipv4"]
      }
    }
