apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-cni
spec:
  template:
    spec:
      initContainers:
        - name: install-cni
          image: galactic-cni:latest
          imagePullPolicy: Never
      containers:
        - name: credential-refresh
          image: galactic-cni:latest
          imagePullPolicy: Never
