apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-gateway
spec:
  template:
    spec:
      # Image override only.
      containers:
        - name: galactic-gateway
          image: galactic-gateway:latest
          imagePullPolicy: Never
