// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package natprog

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NatConnKey struct {
	_         structs.HostLayout
	Family    uint8
	Proto     uint8
	TenantArg uint16
	Sport     uint16
	Dport     uint16
	Saddr     [16]uint8
	Daddr     [16]uint8
	EncapSrc  [16]uint8
}

type NatConnValue struct {
	_           structs.HostLayout
	BackendAddr [16]uint8
	BackendPort uint16
	DestAddr    [16]uint8
	DestPort    uint16
	ShardPort   uint16
	BackendUsid [16]uint8
	Proto       uint8
	Family      uint8
}

type NatShardConfig struct {
	_             structs.HostLayout
	ShardSid      [16]uint8
	ShardPubAddr6 [16]uint8
	Nat64Prefix   [16]uint8
	ShardPubAddr4 uint32
	ServesV6      uint8
	ServesV4      uint8
	Pad           [2]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	NatMapDropReasons      = "drop_reasons"
	NatMapNatConnTable     = "nat_conn_table"
	NatMapNatProgs         = "nat_progs"
	NatMapShardConfigTable = "shard_config_table"
	NatProgNat64Forward    = "nat64_forward"
	NatProgNat64Return     = "nat64_return"
	NatProgNat66Forward    = "nat66_forward"
	NatProgNat66Return     = "nat66_return"
	NatProgNatIngress      = "nat_ingress"
)

// LoadNat returns the embedded CollectionSpec for Nat.
func LoadNat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Nat: %w", err)
	}

	return spec, err
}

// LoadNatObjects loads Nat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NatObjects
//	*NatPrograms
//	*NatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatSpecs struct {
	NatProgramSpecs
	NatMapSpecs
	NatVariableSpecs
}

// NatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatProgramSpecs struct {
	Nat64Forward *ebpf.ProgramSpec `ebpf:"nat64_forward"`
	Nat64Return  *ebpf.ProgramSpec `ebpf:"nat64_return"`
	Nat66Forward *ebpf.ProgramSpec `ebpf:"nat66_forward"`
	Nat66Return  *ebpf.ProgramSpec `ebpf:"nat66_return"`
	NatIngress   *ebpf.ProgramSpec `ebpf:"nat_ingress"`
}

// NatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatMapSpecs struct {
	DropReasons      *ebpf.MapSpec `ebpf:"drop_reasons"`
	NatConnTable     *ebpf.MapSpec `ebpf:"nat_conn_table"`
	NatProgs         *ebpf.MapSpec `ebpf:"nat_progs"`
	ShardConfigTable *ebpf.MapSpec `ebpf:"shard_config_table"`
}

// NatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NatVariableSpecs struct {
}

// NatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatObjects struct {
	NatPrograms
	NatMaps
	NatVariables
}

func (o *NatObjects) Close() error {
	return _NatClose(
		&o.NatPrograms,
		&o.NatMaps,
	)
}

// NatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatMaps struct {
	DropReasons      *ebpf.Map `ebpf:"drop_reasons"`
	NatConnTable     *ebpf.Map `ebpf:"nat_conn_table"`
	NatProgs         *ebpf.Map `ebpf:"nat_progs"`
	ShardConfigTable *ebpf.Map `ebpf:"shard_config_table"`
}

func (m *NatMaps) Close() error {
	return _NatClose(
		m.DropReasons,
		m.NatConnTable,
		m.NatProgs,
		m.ShardConfigTable,
	)
}

// NatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatVariables struct {
}

// NatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNatObjects or ebpf.CollectionSpec.LoadAndAssign.
type NatPrograms struct {
	Nat64Forward *ebpf.Program `ebpf:"nat64_forward"`
	Nat64Return  *ebpf.Program `ebpf:"nat64_return"`
	Nat66Forward *ebpf.Program `ebpf:"nat66_forward"`
	Nat66Return  *ebpf.Program `ebpf:"nat66_return"`
	NatIngress   *ebpf.Program `ebpf:"nat_ingress"`
}

func (p *NatPrograms) Close() error {
	return _NatClose(
		p.Nat64Forward,
		p.Nat64Return,
		p.Nat66Forward,
		p.Nat66Return,
		p.NatIngress,
	)
}

func _NatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nat_bpfel.o
var _NatBytes []byte
