apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    labels:
      topology.kubernetes.io/region: iad
      galactic.io/role: pop
  - role: worker
    labels:
      topology.kubernetes.io/region: iad
      galactic.io/role: route-reflector
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          taints:
            - key: galactic.io/role
              value: route-reflector
              effect: NoSchedule
networking:
  disableDefaultCNI: true
