apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: galactic-router
spec:
  template:
    spec:
      containers:
        - name: galactic-router
          image: __GALACTIC_ROUTER_IMAGE__
          imagePullPolicy: Always
