# ServiceVIPBinding for iad's ns60 backend.
apiVersion: network.datumapis.com/v1alpha1
kind: ServiceVIPBinding
metadata:
  name: ns60-web-iad-worker
  namespace: galactic-system
spec:
  targetRef:
    kind: Node
    name: iad-worker
  vipAddress: 2001:db8:6060::1
  port: 80
  protocol: tcp
  backendAddress: fd20:60:ff03::100:0
  backendPort: 80
  egressKind: veth
