# dfw-worker3's edge gateway overlay.
namespace: galactic-system
resources:
  - ../base
  - bgprouter.yaml
  - bgppeer.yaml
  - networkgateway.yaml
patches:
  - path: node-patch.yaml
    target:
      kind: DaemonSet
      name: galactic-gateway
  # Renames the DaemonSet to this node's name.
  - target:
      kind: DaemonSet
      name: galactic-gateway
    patch: |-
      - op: replace
        path: /metadata/name
        value: galactic-gateway-dfw-worker3
