apiVersion: v1
kind: ConfigMap
metadata:
  name: underlay-config
  namespace: galactic-system
data:
  daemons: |
    zebra=yes
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=no
    fabricd=no
    vrrpd=no
    pathd=no

    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="  -A 127.0.0.1"
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname iad-rr-underlay
    log syslog informational

    interface lo
     ! /48 provides a reachable address for galactic-router peers to connect to on port 1790.
     ipv6 address fc00:0:8::1/48
    !
    interface eth1
     description tr3-facing
     ipv6 address 2001:db8:1:31::2/64
    !

    route-map SET_SRC permit 10
     set src fc00:0:8::1
    !
    router bgp 65000
     bgp router-id 10.255.255.4
     no bgp default ipv4-unicast
     no bgp ebgp-requires-policy
     bgp log-neighbor-changes
     neighbor 2001:db8:1:31::1 remote-as 65100
     !
     address-family ipv6 unicast
      neighbor 2001:db8:1:31::1 activate
      neighbor 2001:db8:1:31::1 allowas-in 1
      neighbor 2001:db8:1:31::1 route-map SET_SRC in
      network fc00:0:8::/48
     exit-address-family
    !

    ipv6 forwarding
  vtysh.conf: |
    service integrated-vtysh-config
