#!/bin/bash
# host-setup.sh — Prepare the host for Containerlab labs.

set -euo pipefail

DUALSTACK=false
PERSIST=true
SYSCTL_CONF=/etc/sysctl.d/99-clab.conf

usage() {
  echo "Usage: $0 [--dualstack] [--no-persist]"
  echo ""
  echo "  --dualstack   Enable IPv4 forwarding in addition to IPv6"
  echo "  --no-persist  Apply sysctls now but do not write to ${SYSCTL_CONF}"
  exit 1
}

for arg in "$@"; do
  case $arg in
    --dualstack) DUALSTACK=true ;;
    --no-persist) PERSIST=false ;;
    --help|-h) usage ;;
    *) echo "Unknown argument: $arg"; usage ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: must run as root (use sudo)" >&2
  exit 1
fi

echo "==> Containerlab host setup"
echo "    dualstack : ${DUALSTACK}"
echo "    persist   : ${PERSIST}"
echo ""

echo "--> Enabling IPv6 forwarding"
sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv6.conf.default.forwarding=1

if [ "$DUALSTACK" = true ]; then
  echo "--> Enabling IPv4 forwarding (dual-stack)"
  sysctl -w net.ipv4.ip_forward=1
else
  echo "--> Disabling IPv4 forwarding (IPv6-only lab)"
  sysctl -w net.ipv4.ip_forward=0
fi

if [ "$PERSIST" = true ]; then
  echo "--> Writing ${SYSCTL_CONF}"
  {
    echo "# Containerlab host requirements"
    echo "# Generated by host-setup.sh"
    echo "net.ipv6.conf.all.forwarding=1"
    echo "net.ipv6.conf.default.forwarding=1"
    if [ "$DUALSTACK" = true ]; then
      echo "net.ipv4.ip_forward=1"
    else
      echo "net.ipv4.ip_forward=0"
    fi
  } >"${SYSCTL_CONF}"
  echo "    written."
fi

echo ""
echo "==> Verification"
echo "    net.ipv6.conf.all.forwarding     = $(sysctl -n net.ipv6.conf.all.forwarding)"
echo "    net.ipv6.conf.default.forwarding = $(sysctl -n net.ipv6.conf.default.forwarding)"
echo "    net.ipv4.ip_forward              = $(sysctl -n net.ipv4.ip_forward)"
echo ""
echo "==> Done. Host is ready for Containerlab."
