apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpc20
  namespace: vpc
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "vpc20",
      "type": "galactic-cni",
      "vpc": "20",
      "vpcattachment": "20",
      "namespace": "galactic-system",
      "ipv6_subnet": "fd00:20:ff02::/48",
      "ipv4_subnet": "172.20.2.0/24",
      "address_families": ["ipv6", "ipv4"]
    }
