apiVersion: v1
kind: ConfigMap
metadata:
  name: underlay-config
  namespace: galactic-system
data:
  daemons: |
    zebra=yes
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    pimd=no
    ldpd=no
    nhrpd=no
    eigrpd=no
    babeld=no
    sharpd=no
    pbrd=no
    bfdd=no
    fabricd=no
    vrrpd=no
    pathd=no

    vtysh_enable=yes
    zebra_options="  -A 127.0.0.1 -s 90000000"
    bgpd_options="  -A 127.0.0.1"
  frr.conf: |
    frr version 9.1
    frr defaults traditional
    hostname sjc-underlay
    log syslog informational

    interface lo
     ! /48 assigns the full SRv6 SID block to this node; eBGP advertises the /48 as the SID range.
     ipv6 address fc00:0:3::1/48
    !
    interface eth1
     description tr2-facing
     ipv6 address 2001:db8:1:20::2/64
    !

    ipv6 route 2001:db8:ff02::/48 Null0
    !
    route-map SET_SRC permit 10
     set src fc00:0:3::1
    !
    router bgp 65000
     bgp router-id 10.255.255.3
     no bgp default ipv4-unicast
     no bgp ebgp-requires-policy
     bgp log-neighbor-changes
     neighbor 2001:db8:1:20::1 remote-as 65100
     !
     address-family ipv6 unicast
      neighbor 2001:db8:1:20::1 activate
      neighbor 2001:db8:1:20::1 allowas-in 1
      neighbor 2001:db8:1:20::1 route-map SET_SRC in
      network 2001:db8:ff02::/48
      network fc00:0:3::/48
     exit-address-family
    !

    ipv6 forwarding
  vtysh.conf: |
    service integrated-vtysh-config
