apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fabric
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
                  - key: galactic.datumapis.com/node
                    operator: In
                    values:
                      - edge
