namePrefix: dfw-
namespace: galactic-system
resources:
  - ../base
patches:
  - path: daemonset-patch.yaml
    target:
      kind: DaemonSet
      name: fabric

configMapGenerator:
  - name: fabric-config
    behavior: merge
    files:
      - frr.conf

