---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: private
  namespace: ns30
spec:
  config: |
    {
      "cniVersion": "1.0.0",
      "name": "private",
      "type": "galactic-cni",
      "vpc": "30",
      "vpcattachment": "30",
      "namespace": "galactic-system",
      "ipv6_subnet": "fd20:30:ff01::/48",
      "address_families": ["ipv6"]
    }
