apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-b
  namespace: ns30
  labels:
    app: private-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-b
  template:
    metadata:
      labels:
        app: private-b
      annotations:
        v1.multus-cni.io/default-network: ns30/private-b
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
      containers:
        - name: netshoot
          image: ghcr.io/datum-cloud/galactic-debug:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
