frr defaults traditional
hostname iad-fabric
log syslog informational

interface lo
 ipv6 address fc00:0:4::1/128

interface eth1
 description tr3-facing
 ipv6 address 2001:db8:1:30::2/64

ipv6 route 2001:db8:ff03:100::/56 Null0

route-map SET_SRC permit 10
 set src fc00:0:4::1

router bgp 65000
 bgp router-id 10.255.255.1
 no bgp default ipv4-unicast
 no bgp ebgp-requires-policy
 bgp log-neighbor-changes
 neighbor 2001:db8:1:30::1 remote-as 65100
 
 address-family ipv6 unicast
  neighbor 2001:db8:1:30::1 activate
  neighbor 2001:db8:1:30::1 allowas-in 1
  neighbor 2001:db8:1:30::1 route-map SET_SRC in
  network 2001:db8:ff03:100::/56
  network fc00:0:4::1/128
 exit-address-family

ipv6 forwarding
