name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    - name: package
      run: |
        mkdir package
        for arch in amd64 arm64; do
          cp galactic-${arch} package/galactic-cli_${arch}
          cp galactic-${arch} package/galactic-cni_${arch}
        done
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        generate_release_notes: true
        files: |
          package/*
